### ISSUE TITLE
[Feature request] Match all EDID

### ISSUE THREAD

**Issue by Anthony25** [phillipberndt/autorandr#100]
Hi,
Could it be possible to setup a profile that matches with all EDID connected to an output?

I regularly have to change from screen to screen (flex office…), so the screen model is the same but the EDID changes. It would be great if I could have a profile triggered when the output is connected, no matter what the EDID is.

Thanks!

**Comment by phillipberndt** [comment]
Please have a look at the wildcard-edid branch: It allows you to edit the setup file and replace the EDID (or parts of it) with an asterisk.

So

    HDMI-0 *

would work.

Does that fit your use-case?

**Comment by Anthony25** [comment]
Nice, thanks a lot!

I will test it tomorrow, but it seems to exactly fit my use-case.

**Comment by Anthony25** [comment]
@phillipberndt: I tested this morning, everything is working great. Thanks!

**Comment by phillipberndt** [comment]
Good :-) Merged to master.
