### ISSUE TITLE
Suggestion for a GUI

### ISSUE THREAD

**Issue by Vladimir-csp** [phillipberndt/autorandr#101]
There is a great standalone GUI tool for XRandr also written in python:
https://christian.amsuess.com/tools/arandr/
But its configuration storage and load mechanics are rather dull (sh scripts).  I once made a crude local fork of it to work with [my own xrandr daemon](https://github.com/Vladimir-csp/rerandr3). Basically gutting everything related to profile save/load and instead just executing `rerandr3 save` on apply. It worked for me.

Consider either collaborating with arandr or forking it to make a frontend for autorandr. It is a good match IMHO.

**Comment by phillipberndt** [comment]
Good thinking, but nothing I have the time to provide :-) Feel free to port, I'll happily add a link to the readme.
