### ISSUE TITLE
systemd unit prevents launching permanent processes

### ISSUE THREAD

**Issue by languitar** [phillipberndt/autorandr#111]
I had a long standing issue with relaunching polybar via the udev hook after a display change. The bar always appeared shortly and then disappeared (see: https://github.com/jaagr/polybar/issues/173). I was finally able to track the issue down to the systemd unit provided with autorandr. What happens in case the connected displays are changed is the following:

1. udev detects the change and calls `systemd start autorandr.service`
1. The systemd unit starts `autorandr --batch`
1. `autorandr --batch`effectively calls the postswtich hooks in the user sessions, which I use to launch polybar using a bash script
1. The bash script uses `polybar &` to detach the newly spawned processes to "keep them alive".

The issue is that the default setting for systemd units is to kill all members of the control group of the initially called process (`autorandr --batch`) once this process has exited. Without black magic, everything in the postswitch hooks is in the same cgroup and thus all detached processes intended to be long-running are directly killed again once the `autorandr --batch` call finished.

I am not sure whether this decision is intentional, but it makes uses cases as mine pretty hard to realize. Thus, I'd propose to add `KillMode=process` to the systemd unit to avoid the control group killing behavior.

**Comment by phillipberndt** [comment]
Sounds reasonable. No, it's not intentional. Would you file a PR?

**Comment by languitar** [comment]
Done. Can this be ported back to a stable release so that distributions can pick this up?

**Comment by phillipberndt** [comment]
I'll just issue a new release soon! :-)

**Comment by phillipberndt** [comment]
Released as part of 1.6.

**Comment by pmuller** [comment]
Ubuntu doesn't define `KillMode=process` in its systemd service.

The default service definition can be easily be overridden running `systemctl edit autorandr` and adding this snippet:

```
[Service]
KillMode=process
```

:warning: Doing this fixes the issue, but introduce another one: #252

**Comment by FichteFoll** [comment]
As a modern alternative to this problem (that I did not actually encounter), you can also opt to spawn the polybar processes in transient systemd units using `systemd-run --user`, which will ensure that they are spawned and managed by the user session's systemd daemon and not by autorandr.
