### ISSUE TITLE
Event detection using Xorg server events rather than udev

### ISSUE THREAD

**Issue by rliou92** [phillipberndt/autorandr#124]
I propose subscribing to events from the user's Xorg server rather than installing a udev rule as a more direct way of triggering the program to run. Using the udev rule runs the script as root and thus the program doesn't know about which user wants to have their displays reconfigured, correct? Subscribing to the Xorg server events using xcb solves that problem. The tradeoff is that then you must interface with C code. I'm willing to submit a pull request if you are open to the idea.

**Comment by phillipberndt** [comment]
There used to be a tool called srandr for that on bitbucket.. can't find it just now.

As long as this'd be mostly independent code, that is, the python code works without this, too, and libxcb isn't added to the (default) dependency list, I'd be happy to include this. I guess my favorite'd be a completely independent tool in contrib/, but an optional python module and a --daemon mode would work for me, too.

By the way, --batch does spawn off children per x11 session as the correct user. So if it's security or convenience you're after, then there's no need for this. But in some situations udev doesn't work reliable (xrandr called too early), so having this in would still be useful.

**Comment by rliou92** [comment]
Yes, I agree that the program runs as the correct user, but autorandr has to first fork for all users with an X11 session.  This is because the program is being triggered from udev, which runs autorandr as root, not as the user who wants his display reconfigured. I was proposing this idea mainly for simplicity, as then the program can be run directly as the user. If systemd is preferred then the program could be run with the `--user` flag.

For srandrd I found it here: https://github.com/jceb/srandrd
I have also written my own program that does the same thing and more which can be found in my repos. I'm not quite sure if udev is behaving incorrectly then this idea will solve that, because I think fundamentally udev handles the event, xorg sees it and then sends its own event. 

By completely independent tool, do you mean a program like srandrd? I can write one like that written in python or C.

**Comment by phillipberndt** [comment]
Basically, yes. I don't care much whether the tool is able to other things than calling autorandr when the configuration changes. It can be autorandr specific of course. The important direction for "independent" is the other way around: If a user decides to use autorandr without depending on libxcb-dev and a c compiler or a libpyxcb (if that exists), then that should still be possible.

**Comment by rliou92** [comment]
Got it! I think I will write a small program in C to do this.

**Comment by phillipberndt** [comment]
Merged.
