### ISSUE TITLE
Systemd unit shows "inactive (dead)"

### ISSUE THREAD

**Issue by cvincent** [phillipberndt/autorandr#125]
I've added the systemd unit from contrib at `/etc/systemd/system` and enabled and started the service. When I plug or unplug an external monitor, nothing seems to happen (although my `i3blocks` bar does flash momentarily as though it's reloading), however I can manually run `autorandr -c` and it behaves correctly. When I run `systemctl status autorandr.service` I get the following output:

```
● autorandr.service - autorandr execution hook
   Loaded: loaded (/etc/systemd/system/autorandr.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
```

On a previous laptop it had worked such that the new display configuration would automatically load as expected when adding or removing displays.

**Comment by phillipberndt** [comment]
The systemd unit only serves as an entry point for the udev rule, it's not a service. See the make file. Did you set up that as well?

**Comment by cvincent** [comment]
On closer inspection, it looks like it may have to do with how udev is un/affected by the proprietary Nvidia driver. Will report back if I find a solution.

**Comment by cvincent** [comment]
I got it working, with the help of a separate script:
https://github.com/nalipaz/poll-xrandr

Rather than relying on udev, which from my research seems to work inconsistently on some configurations, this runs in the background and polls xrandr to detect changes in displays, calling `autorandr --change --force` if anything changes. I've configured i3 to launch it on boot.

Also, rather than grab the latest release of poll-xrandr, I used the script currently on master, which seems to fix an issue with it thinking it's already running when you try to start it.

Hope this helps someone else in my conundrum searching the internet for a solution. Closing the issue.

**Comment by fiskhest** [comment]
@cvincent thanks, your tip helped in my troubles working around udev & nvidia proprietary.

**Comment by welcoMattic** [comment]
Thank you @cvincent your solution helps me!

**Comment by fdw** [comment]
I found another way to make udev work with nvidia:
```
echo "options nvidia-drm modeset=1" >> /etc/modprobe.d/nvidia-modeset.conf
```

Maybe this helps someone :)

**Comment by dirodriguezm** [comment]
> I found another way to make udev work with nvidia:
> 
> ```
> echo "options nvidia-drm modeset=1" >> /etc/modprobe.d/nvidia-modeset.conf
> ```
> 
> Maybe this helps someone :)

This didn't help me. Is there a way to actually fix this instead of using a custom script ? 
I think that this issue should be reopened
