### ISSUE TITLE
"Strict mode" to fingerprint with the modes along with the EDID

### ISSUE THREAD

**Issue by seirl** [phillipberndt/autorandr#126]
I have an HDMI splitter at home. I have two screens, *screen1* and *screen2*, plugged in this HDMI splitter. I would like to have autorandr change my configuration depending on which screen is currently "active" on the splitter.

The problem is, the splitter always give the same EDID. (Maybe it's impossible to forward the current screen's EDID? Or maybe my splitter is just shitty, I don't know.) So autorandr isn't able to detect which screen is currently used.

While pressing on the splitter's button, I diffed the output of `xrandr -q --verbose` to see if I could use something else than the EDID to differentiate between the two screens, and the *only* thing that changes is the list of modes.

So, to experiment, I manually changed the EDID computation to append a sha256 of the list of modes/resolutions/rates at the end of the EDID:

```diff
diff --git a/autorandr.py b/autorandr.py
index 1e980f6..a98d55a 100755
--- a/autorandr.py
+++ b/autorandr.py
@@ -42,6 +42,7 @@ from collections import OrderedDict
 from distutils.version import LooseVersion as Version
 from functools import reduce
 from itertools import chain
+from hashlib import sha256
 
 if sys.version_info.major == 2:
     import ConfigParser as configparser
@@ -317,6 +318,14 @@ class XrandrOutput(object):
         else:
             edid = "%s-%s" % (XrandrOutput.EDID_UNAVAILABLE, match["output"])
 
+        if edid is not None:
+            modes_serialize = ' '.join(
+                '{}:{}:{}'.format(mode['width'], mode['height'], mode['rate'])
+                for mode in sorted(modes, key=lambda mode: mode['name'])
+            )
+            modes_fingerprint = sha256(modes_serialize.encode()).hexdigest()
+            edid = edid + ':' + modes_fingerprint
+
         if not match["width"]:
             options["off"] = None
         else:
```

And it works! But now the generated EDID/fingerprints aren't backwards-compatible, so it breaks the previous configurations.

I don't have an in-depth knowledge of the codebase and a clear view of what would be the best way to address that and make this code nicer and more generic. So, do you think adding a "strict mode" option to autorandr, that doesn't only fingerprints the setups with the EDID but also with the modes, would be a good idea?

Thanks!

**Comment by phillipberndt** [comment]
Sounds like a use case for the `block` hook to me!? Adding modes to the hardware detection for purposes other than auto-configuration seems too much of a hack and too rare a use case to consider right now..

**Comment by seirl** [comment]
Thanks, I wasn't aware of the `block` hook.

I wrote two really ugly block scripts, but they do the job:

```bash
#!/bin/bash           
 
! xrandr --query --verbose |
    grep '^HDMI-0' -A1000 |
    tail -n+2 |
    grep -B1000 -m1 '^[A-Za-z]' |
    grep -q 1680x1050
```

I guess that'll do! :-)
