### ISSUE TITLE
Pyhton version does not handle unused connected displays

### ISSUE THREAD

**Issue by RasmusWL** [phillipberndt/autorandr#13]
Thanks for keeping this project going. I started building my own Python version from scrap after realising that the `wertabyte` repo didn't work. (if you're in touch with him, maybe you can ask him to put a disclaimer on the top of the readme?)

Currently your python version does not work. If there's a display connected, but not currently used by `xrandr`, I get the current output:

```
LVDS1 connected (normal left inverted right x axis y axis)
```

However, your RegEx requires that if a display is connected, it must also have `<with>x<height>+<x>+<y>`, which is clearly not true.

---

The main point is: a display can be connected, but not in use. This means there are 3 statuses: (1) in use, (2) idle (connected but not in use), (3) disconnected.

Currently your code relies on the `"off"` property for most of it's logic, so this is a non-trivial change which I think is better left off to you :smile:

**Comment by phillipberndt** [comment]
Thanks! wertabyte seems to be quite occupied, I doubt that he'll take the effort. (He didn't even add a note that autorandr is opensource to his readme, it's hidden in the issue section..)

A display that is connected, but unused in the current configuration, is still `--off` to xrandr, unless I don't get your use-case correctly. Does https://github.com/phillipberndt/autorandr/commit/2181c8ef025f4e0997a4393832b3d686f5990d3d resolve this for you?
