### ISSUE TITLE
No change after reboot

### ISSUE THREAD

**Issue by ptrstn** [phillipberndt/autorandr#131]
Hello, 

first of all thank you very much for this tool. It works extremely good and is such a time saver!

There's just a little thing that I do not understand:
When I reboot my machine ```autorandr``` does not automatically apply the detected profile, even though I have ```enabled``` and ```started``` ```autorandr.service```.

As you can see the correct profile is detected but not loaded:

```bash
$ autorandr
work (detected)
mobile
```

```bash
# systemctl status autorandr
● autorandr.service - autorandr execution hook
   Loaded: loaded (/usr/lib/systemd/system/autorandr.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Dec 05 09:46:22 carbon systemd[1]: Starting autorandr execution hook...
Dec 05 09:46:22 carbon systemd[1]: Started autorandr execution hook.
Dec 05 09:46:22 carbon systemd[1]: Starting autorandr execution hook...
Dec 05 09:46:22 carbon systemd[1]: Started autorandr execution hook.
```

Manually starting ```autorandr.service``` does load the profile though:

```bash
# systemctl start autorandr
```

```bash
# systemctl status autorandr
● autorandr.service - autorandr execution hook
   Loaded: loaded (/usr/lib/systemd/system/autorandr.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Dec 05 09:46:22 carbon systemd[1]: Starting autorandr execution hook...
Dec 05 09:46:22 carbon systemd[1]: Started autorandr execution hook.
Dec 05 09:46:22 carbon systemd[1]: Starting autorandr execution hook...
Dec 05 09:46:22 carbon systemd[1]: Started autorandr execution hook.
Dec 05 09:46:56 carbon systemd[1]: Starting autorandr execution hook...
Dec 05 09:46:56 carbon autorandr[1250]: autorandr running as user ptrstn (started from batch instance)
Dec 05 09:46:56 carbon autorandr[1250]: work (detected)
Dec 05 09:46:56 carbon autorandr[1250]: mobile
Dec 05 09:46:56 carbon autorandr[1250]: Running autorandr as ptrstn for display :0
Dec 05 09:46:56 carbon systemd[1]: Started autorandr execution hook.
```

```bash
$ autorandr
work (detected) (current)
mobile
```

I am using Archlinux and i3 with [startx](https://wiki.archlinux.org/index.php/Xinit#Autostart_X_at_login)/tty as login method.
i3 is started with ```exec i3``` in ```.xinitrc```.

Autorandr was installed through the [arch community package](https://www.archlinux.org/packages/community/any/autorandr/).

What am I missing? Do I have to ```exec``` ```autorandr --change``` in the i3 config?

Thanks!

**Comment by ptrstn** [comment]
In case anyone else is asking himself the same question: 
Putting ```autorandr --change``` just before ```exec i3``` in ```.xinitrc``` does exactly what I wanted. I should have known, sorry.

**Comment by prosoitos** [comment]
Thank you @ptrstn! I was having the same issue :slightly_smiling_face: 

Now, as a side note, I am on the same setting as you (Archlinux, i3, startx) and I am not running any `autorandr.service`. All I ever did was to run `autorandr --save mobile` and `autorandr --save docked` and autorandr gets launched automatically, somehow (I have no idea how...). I am not launching it through `.xinitrc` either.
