### ISSUE TITLE
Profile sort by mtime is not compatible with original sort by name behavior

### ISSUE THREAD

**Issue by sparr** [phillipberndt/autorandr#134]
From other issues I see that the choice to sort by mtime was intentional, so I expect this issue to be closed, but I thought it should be documented for future people who are confused.

The original bash script sorts profiles by name, requiring the user to rename matching profiles to get the right one to apply first. The python script sorts profiles by modification time on the configuration, requiring the user to `touch` the config of the profiles in the order they should be listed and applied.

I happen to think that the named sort is better and more intuitive when I am looking at my ~/.autorandr/ and want to know the order of the profiles.

**Comment by phillipberndt** [comment]
See #16 for why it's being done this way. Documentation could improve in general, agreed - I'll happily merge related PRs.
