### ISSUE TITLE
Failed to apply profile 'home' (line 252):   not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by SpencerApel** [phillipberndt/autorandr#135]
Was a long error message, so here is a pastebin with bash syntax: https://pastebin.com/JAiq8ns2

I used to use Arandr but switch to autorandr because automatic.
But I have had trouble with the orientation of my display.
I have my 2nd monitor to the left of my screen, but have to move my mouse to the right of the screen to get to the 2nd display.

The error states: 

autorandr -c
home (detected)
mobile
Failed to apply profile 'home' (line 252):
  not enough values to unpack (expected 2, got 1)

From what I could gather, which probably is not that much, it seems to be an issue with detecting the 2nd display.

Also ran the '--debug' command:

[spencer@archlinux ~]$ autorandr --debug
home (detected)
| Differences between the two profiles:
| [Output eDP-1] Option --pos (= `0x0') is `1920x0' in the new configuration
| [Output HDMI-1] Option --pos (= `1366x0') is `00' in the new configuration
\-
mobile

**Comment by phillipberndt** [comment]
The `00` is what's off. The code expects positions to be in the format `0x0`. What's weird is why it's being stored this way. Hotfix for you now is to edit the configuration file manually and replace the `00` parameter for `pos` with `0x0`. What'd help finding out how this could go wrong is the `xrandr --verbose` output at a point in time where `autorandr -s home` creates a faulty profile with the `00` in it - from what I can gather it shouldn't for the output you attached.

**Comment by SpencerApel** [comment]
Just to clarify, I am using a laptop. eDP-1 is my laptop display and HDMI-1 is my 2nd monitor that is to the left of my laptop display (autorandr thinks it is to the right)

Alright, so I changed my home profile config to:

> output DP-1
off
output HDMI-2
off
output eDP-1
mode 1366x768
pos 1920x0
primary
rate 60.00
output HDMI-1
mode 1920x1080
pos 0x0
rate 60.00

Then I ran `autorandr --debug`

> home (detected)
| Differences between the two profiles:
| [Output HDMI-1] Option --pos (= `1366x0') is `0x0' in the new configuration
| [Output eDP-1] Option --pos (= `0x0') is `1920x0' in the new configuration
\-
mobile

Still have the error. Here is a pastebin of my output after running `xrandr --verbose`
https://pastebin.com/gtSHHLk0

**Comment by phillipberndt** [comment]
So if you explicitly run `autorandr -l mobile`, and then `autorandr -c` to reload the home configuration - does the tool then have the same problem?

And to clarify: Does your system run autorandr when the session comes up?  What you describe would be expected if nothing runs `autorandr -c` before you do.

**Comment by SpencerApel** [comment]
Yeah when I run those commands and it is working now.
I did have 'exec autorandr' but for some reason the '-c' option was not flagged. Anyways, it all is working now. Thanks for the help
