### ISSUE TITLE
Failed to apply profile 'horizontal' invalid literal for int() with base 10: '1080i'

### ISSUE THREAD

**Issue by magnen** [phillipberndt/autorandr#141]
Failed to apply profile 'horizontal' (line 641):
  invalid literal for int() with base 10: '1080i'
This appears to be a bug. Please help improving autorandr by reporting it upstream:
https://github.com/phillipberndt/autorandr/issues
Please attach the output of `xrandr --verbose` to your bug report if appropriate.

xrandr --verbose:
https://pastebin.com/R62LNbrP

**Comment by phillipberndt** [comment]
Could you please try with the latest version from this repository? I believe this issue has been fixed already.

**Comment by RasmusWL** [comment]
It would be cool to include the version of autorandr in the default bug-report hinting text. Then it becomes amazingly easy to figure out the bug is because someone is using an old version :smile:

**Comment by magnen** [comment]
My most humblest apology!

$ autorandr --version
autorandr 1.7

**Comment by RasmusWL** [comment]
Oh my, I see that what I wrote sounds quite passive-aggressive. My most humblest apology, that was not intended :blush: 

I only meant for @phillipberndt to consider adding this in the future, so it's easy to figure out. I would even go for adding the git-sha for the most recent commit, so there is no doubt (but I'm not sure how difficult that would be).

**Comment by phillipberndt** [comment]
..so *does* this still happen with the git version?

**Comment by magnen** [comment]
Not entirely sure what happened (did a system update, might have pulled in some other changes as well) but the problem no longer exists. Thanks :)
