### ISSUE TITLE
mandb should not be called during install

### ISSUE THREAD

**Issue by dvzrv** [phillipberndt/autorandr#144]
Hi! I'm packaging autorandr for Arch Linux. During upgrading to 1.8 I realized, that a man page was added (awesome!).
However, mandb should not be [called during the installation process](https://github.com/phillipberndt/autorandr/blob/master/Makefile#L136):

Usually, mandb (updating the index caches) runs as a cron job or systemd timer on Linux distributions. The system administrator is responsible for running this (or rather: the distribution configures it to be automatically run). Additionally, the process for package managers is to install a certain package and then run hooks depending on what was added to the filesystem (e.g. update mandb caches, update udev database, etc.). 
In any case, this should be considered a separate process!

If this definitely needs to be in the Makefile, it needs to be a separate target, that has nothing to do with the install or uninstall target (or just be added as an info echo similiar to the udev/systemd info).

**Comment by phillipberndt** [comment]
Yup, agreed. Is it easy for you to patch this out for now, or would you prefer a patch release?

cc @somers-all-the-time

**Comment by dvzrv** [comment]
No worries, I removed it for the package build. Just wanted to give a heads up! :)

**Comment by phillipberndt** [comment]
Made a patch release anyway before other maintainers run into the same problem. All 1.8.1 does is remove the mandb call. Thanks again!
