### ISSUE TITLE
Spelling issue in repository description

### ISSUE THREAD

**Issue by andrewnicolalde** [phillipberndt/autorandr#148]
This is such a minor issue I considered just ignoring it but I figured what the hell.

The current repository description reads:
`
Auto-detect the connect display hardware and load the appropriate X11 setup using xrandr
`
It should probably read:
`
Auto-detect the connected display hardware and load the appropriate X11 setup using xrandr
`
With the difference being word 3 (connect vs connected).

**Comment by phillipberndt** [comment]
Blindly copied from the original upstream repo and never updated :) Thanks, fixed!
