### ISSUE TITLE
autorandr initializes screens in the wrong order

### ISSUE THREAD

**Issue by Sayrus** [phillipberndt/autorandr#150]
**Current behaviour:**
Autorandr initializes the right screen alone then initializes the others. This lead the right screen to overlap the left screen.

```
autorandr --change --debug
cri-dock-l2 (detected)
laptop (current)
Loading profile 'cri-dock-l2'
| Differences between the two profiles:
| [Output DP1-2] The output is disabled currently, but active in the new configuration
| [Output DP2-1] The output is disabled currently, but active in the new configuration
| [Output eDP1] The output is currently enabled, but inactive in the new configuration
| [Output DP2-2] The output is disabled currently, but active in the new configuration
\-
Going to run:
xrandr --fb 5040x1920 --output eDP1 --off --output DP2-2 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 3840x0 --rate 59.95 --reflect normal --rotate right
xrandr --fb 5040x1920 --output DP2-1 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 0x335 --rate 59.95 --reflect normal --rotate normal --output DP1-2 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 1920x335 --primary --rate 59.95 --reflect normal --rotate normal

The configuration change did not go as expected:
| Differences between the two profiles:
| [Output DP2-2] Option --pos (= `0x0') is `3840x0' in the new configuration
\-
```

![image](https://user-images.githubusercontent.com/22404472/56753534-0431d300-678b-11e9-842f-75b24225b324.png)

**Expected behaviour:**
![image](https://user-images.githubusercontent.com/22404472/56753730-81f5de80-678b-11e9-8abd-9c3474e76032.png)

**Notes:**
Running it a second time lead to the expected result.

**Configuration:**
```
output DP1
off
output DP1-1
off
output DP1-3
off
output DP2
off
output DP2-3
off
output HDMI1
off
output HDMI2
off
output VIRTUAL1
off
output VIRTUAL2
off
output eDP1
off
output DP2-1
mode 1920x1200
pos 0x335
rate 59.95
output DP1-2
mode 1920x1200
pos 1920x335
primary
rate 59.95
output DP2-2
mode 1920x1200
pos 3840x0
rate 59.95
rotate right
```
I am using the ArchLinux autorandr package.

The configuration is generated using --save. I have no idea how autorandr works internally. If you need any information, you can ping me and I'll provide them.

**Comment by phillipberndt** [comment]
Thanks for the detailed description, and sorry for the delay.

Autorandr intentionally doesn't touch more than two outputs at a time since that leads to known issues with a variety of cards. The command line looks correct to me, it says that `DP2-2` should go to `3840x0` of a `5040x1920` frame buffer. Apparently another bug in a video driver *sigh*

Maybe it's as simple as making sure that the monitor at `0x0` comes first? Please check what the following change does:

In autorandr.py, line 748, replace

    enable_outputs.append(option_vector)

with

    if current_configuration[output].options.get("pos", "0x0") == "0x0":
        enable_outputs.insert(0, option_vector)
    else:
        enable_outputs.append(option_vector)

**Comment by Sayrus** [comment]
Hello,

Sorry for the late answer.
I tried your fix but the following happens:
```python
current_configuration[output].options.get("pos", "0x0") == "0x0"
```
always evaluate to true as .get("pos", var) always returns var.

I tried to force my left-most display to be the first and to use 0x0:
```
xrandr --fb 5040x1920 --output eDP1 --off --output DP1-1 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 0x0 --rate 59.95 --reflect normal --rotate normal
xrandr --fb 5040x1920 --output DP2-2 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 1920x0 --rate 59.95 --reflect normal --rotate normal --output DP1-2 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 3840x0 --primary --rate 59.95 --reflect normal --rotate right
```
Great it worked!
Now let's try with the original outputs:
```
xrandr --fb 5040x1920 --output eDP1 --off --output DP1-1 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 0x335 --rate 59.95 --reflect normal --rotate normal
xrandr --fb 5040x1920 --output DP1-2 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 3840x0 --primary --rate 59.95 --reflect normal --rotate right --output DP2-2 --gamma 1.0:1.0:1.0 --mode 1920x1200 --pos 1920x335 --rate 59.95 --reflect normal --rotate normal
```

Nearly worked, the first screen is pulled to top as 0x335 is rewritten to 0x0.

Okay let's try to create a fix using what you gave me:
- If we want to initialize the left-most screen, we need to get coordinates starting with `0x`
- We need to check on the new_configuration as current_configuration might (usually does not as far as I can tell) not have the position

```python
if new_configuration[output].options.get("pos", "0x0").startswith("0x"):
    enable_outputs.insert(0, option_vector)
else:
    enable_outputs.append(option_vector)
```

I still don't have any solution for the screen y being reseted. However this one seems to be linked with something under the hood rather than autorandr.

**Comment by phillipberndt** [comment]
Ah, that bug report is very helpful. Thanks for diving into this :) Sounds as if the following would work:

* Always put the monitor with the smallest `min(pos_x, pos_y)` first
* If either is non-zero, fix the position in a second xrandr call, because xrandr will move the monitor to the origin

**Comment by Sayrus** [comment]
Sorting by `min(pos_x, pos_y)` might be overkill and hard: you have to do the exact same implementation as xrandr (is x more important than y, i.e. is 400x0 first or is it 0x400?). I have a PR ready for:

* While inserting, if we find a monitor with 0x0, we insert it in front
* If we did not find not find any 0x0 monitor, fix the position in a second xrandr call

We enable the two first output of `enable_outputs` as both might have been shifted by xrandr.

This way you avoid sorting your output list and you 

Here is a diff of the patch:
```diff
@@ -688,6 +688,7 @@ def get_fb_dimensions(configuration):
 
 def apply_configuration(new_configuration, current_configuration, dry_run=False):
     "Apply a configuration"
+    require_xrandr_fix = True
     outputs = sorted(new_configuration.keys(), key=lambda x: new_configuration[x].sort_key)
     if dry_run:
         base_argv = ["echo", "xrandr"]
@@ -748,7 +749,11 @@ def apply_configuration(new_configuration, current_configuration, dry_run=False)
                         except ValueError:
                             pass
 
-            enable_outputs.append(option_vector)
+            if new_configuration[output].options.get("pos", "0x0") == "0x0":
+                enable_outputs.insert(0, option_vector)
+                require_xrandr_fix = False
+            else:
+                enable_outputs.append(option_vector)
 
     # Perform pe-change auxiliary changes
     if auxiliary_changes_pre:
@@ -782,6 +787,12 @@ def apply_configuration(new_configuration, current_configuration, dry_run=False)
         if call_and_retry(argv, dry_run=dry_run) != 0:
             raise AutorandrException("Command failed: %s" % " ".join(argv))
 
+    if require_xrandr_fix:
+        argv = base_argv + list(chain.from_iterable(enable_outputs[:2]))
+        if call_and_retry(argv, dry_run=dry_run) != 0:
+            raise AutorandrException("Command failed: %s" % " ".join(argv))
+
+
 
 def is_equal_configuration(source_configuration, target_configuration):
     """

```

Note that both our algorithm does not handle the case where you have more than two screens shifted:
![image](https://user-images.githubusercontent.com/22404472/58507391-fad4c580-8191-11e9-8e00-44de62294b9c.png)

In this case (if we assume than the enable_output list is from left to right):
DP1-1 get shifted top
DP2-2 get shifted top
eDP1 get shifted top (but keep its offset compared to DP2-2)
DP1-2 get the right position

Then with the fix:
DP1-1 get the right position
DP2-2 get the right position
eDP1 is still in the wrong position

The only solution I see to correctly place all the monitors is to try to fix the position of every output once they have been initialized if no 0x0 monitor has been found. (See pull request #157 )

If I missed anything, feel free to correct the PR or ask me to do so!

**Comment by phillipberndt** [comment]
I'm not happy about just setting everything a second time. That's too much brute force..

If I get you [and the xrandr code](https://github.com/raboof/xrandr/blob/master/xrandr.c) correctly what we need to do for the minimal-invasive solution is
* if there is no output with `x=0` or `y=0` in the configuration move the outputs ourself to the origin to make sure other outputs are placed correct relatively to the topmost/leftmost one at least
* enable the output at `x=0` first
* if the output at `y=0` is a different output, then
  * if both can be enabled in the same xrandr call (within the rules described in `apply_configuration` just make sure that this happens
  * if not, inject another call that will reposition the one at `x=0` correctly vertically within the xrandr invocation that enables the `y=0` output

That would work, or do I miss something, too?

**Comment by Sayrus** [comment]
That sounds way better as you will avoid misplacing all the other screen and brute forcing the correct position.

I don't see any missing case.

The only thing I see is on the case where there is no x=0/y=0 (isn't that a misconfiguration as xrandr will basically destroy what you gave it?). It is not specified that once we shifted every output, we must to check again for any x=0 / y=0 case.

I'll try to implement it as soon as possible.

**Comment by phillipberndt** [comment]
> (isn't that a misconfiguration as xrandr will basically destroy what you gave it?).

Right. It'd be an alternative to refuse to store profiles in that case, failing with an error message that says that `xrandr` cannot recreate such a configuration.

**Comment by Sayrus** [comment]
I updated the PR but I am still annoyed by how I insert into `enable_outputs`. I'll test it on several screen layout.

**Comment by blelump** [comment]
The same has happened for the configuration consisting of 3 screens: 1 laptop + 2 monitors, whereas laptop is configured to be disabled. After loading profile for such setup, the `DP2-2` given above sticks to the left corner, whereas I'd expect similar behavior to what has been shown on `Expected behaviour` .

Applying #157 resolves this issue.

**Comment by phillipberndt** [comment]
Thanks for the feedback. Merging.
