### ISSUE TITLE
Consider detaching fork

### ISSUE THREAD

**Issue by thumphries** [phillipberndt/autorandr#155]
This repo is now the primary home for autorandr, but it doesn't show up in Google results for `autorandr`, `autorandr github`, or `autorandr fork`! GitHub and Google both think the original repo is the important one.

You should consider [contacting GitHub support and requesting they detach your fork](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork)! They can do it without disturbing anything.

Thanks for maintaining!

**Comment by phillipberndt** [comment]
I have reached out to them, and also asked whether it's possible to just swap the relation and make wertarbyte's repository a fork of this one instead. I'll post an update once I get something back.

**Comment by phillipberndt** [comment]
It's been detached. Swapping would only have been possible by upstream's request.
