### ISSUE TITLE
autorandr thinks it switched config but it didn't

### ISSUE THREAD

**Issue by antoyo** [phillipberndt/autorandr#158]
Hi.
I started using autorandr, but it does not seem to work as expect:
when I plug my monitor, it loads the config correctly, but not when I unplug it (it does not run the right xrandr command to turn off the monitor).
If I run:
```
autorandr --load undocked
```
it says the config is already loaded, but if I run:
```
autorandr --load undocked --force
```
it runs the config correctly.
Am I missing something or is this a bug?
Thanks.

**Comment by digilist** [comment]
I am experiencing the same issue when I unplug my monitor, that the config is not loaded correctly.

**Comment by phillipberndt** [comment]
What does `xrandr --verbose` show for the disconnected monitor? Do you run this with a version of autorandr that has [this commit in](https://github.com/phillipberndt/autorandr/commit/4af13f0a62d6a937d487bc3eb0d66522cdbb61b7)?

**Comment by antoyo** [comment]
It indeed works with `master`. I was using version 1.8.1.
Thanks.
