### ISSUE TITLE
Python: identical profiles, choose last used (?)

### ISSUE THREAD

**Issue by RasmusWL** [phillipberndt/autorandr#16]
I use two different setups when I have my external monitor plugged in. Would be nice if `--change` chose the one last used. I was thinking of just `touch`'ing the `setup` files (for compatibility reasons). Are you OK with this?

**Comment by phillipberndt** [comment]
Sounds reasonable. IMO, you should only update the mtime if the profile order would change though, i.e. if there were other detected candidates earlier in the processing of the configuration files. This would spare users that only have one configuration per setup from the additional write access to the disk.

**Comment by RasmusWL** [comment]
Uhh, fancy. Have to try it out soon. Thanks :)
