### ISSUE TITLE
blank screen for 15 seconds after loading configuration

### ISSUE THREAD

**Issue by PDiracDelta** [phillipberndt/autorandr#168]
When I lock screen on Ubuntu 18.04, the OS loses the autorandr setup (this is another Issue I would like to solve). After login, it loads my dual monitor setup is incorrect. When I load the correct setup using autorandr, it takes 15(!) seconds to load it, during which the screens are both black.

/var/log/syslog repeats this sequence of messages about 3 times per second during this 15 second blackout:
```
Oct 29 12:49:59 pdiracdelta-laptop /usr/lib/gdm3/gdm-x-session[1614]: (II) modeset(0): EDID vendor "LGD", prod id 1390
Oct 29 12:49:59 pdiracdelta-laptop /usr/lib/gdm3/gdm-x-session[1614]: (II) modeset(0): Using hsync ranges from config file
Oct 29 12:49:59 pdiracdelta-laptop /usr/lib/gdm3/gdm-x-session[1614]: (II) modeset(0): Using vrefresh ranges from config file
Oct 29 12:49:59 pdiracdelta-laptop /usr/lib/gdm3/gdm-x-session[1614]: (II) modeset(0): Printing DDC gathered Modelines:
Oct 29 12:49:59 pdiracdelta-laptop /usr/lib/gdm3/gdm-x-session[1614]: (II) modeset(0): Modeline "1920x1080"x0.0  138.60  1920 1968 2000 2080  1080 1083 1088 1111 -hsync -vsync (66.6 kHz eP)
Oct 29 12:49:59 pdiracdelta-laptop /usr/lib/gdm3/gdm-x-session[1614]: (--) modeset(0): HDMI max TMDS frequency 170000KHz
```

**How can I make autorandr load faster**, and if possible, how can I make Ubuntu not lose the autorandr configuration after logout or lock? 
Tricky detail: I don't want to hardwire the settings into xorg.conf because then it displays an error when I boot my laptop without the second monitor connected. I'd like to conditionally load the correct autorandr settings only when the display is connected.

**Comment by phillipberndt** [comment]
Could it be that you have your window manager's autoconfiguration still enabled? autorandr and it would fight over the setup, which might explain the delay..?!

**Comment by PDiracDelta** [comment]
> Could it be that you have your window manager's autoconfiguration still enabled? autorandr and it would fight over the setup, which might explain the delay..?!

Possibly; how would I check that? Do you mean `~/.xprofile`?

**Comment by phillipberndt** [comment]
For Gnome, this used to work:

`gsettings set org.gnome.settings-daemon.plugins.xrandr active false`

**Comment by PDiracDelta** [comment]
> For Gnome, this used to work:
> 
> `gsettings set org.gnome.settings-daemon.plugins.xrandr active false`

That does what it should do but doesn't change much with regards to the blank screen time, still 3-4 seconds. Is that a 'normal' duration? If so, might want to close this issue, it's probably something that has somehow been fixed.

**Comment by phillipberndt** [comment]
That's somewhat normal, the tool has quite a few safeguards against malfunctioning drivers that make it a bit slower than necessary. Try the following: Disable the autorandr and gnome automation, then run autorandr in `--dry-run` mode. This will probably print more than one command. Check if merging the command lines into a single one works for you and whether it does speed up the process. If it does then we can adjust autorandr to allow configuring using a single command, too..

**Comment by PDiracDelta** [comment]
> That's somewhat normal, the tool has quite a few safeguards against malfunctioning drivers that make it a bit slower than necessary. Try the following: Disable the autorandr and gnome automation, then run autorandr in `--dry-run` mode. This will probably print more than one command it would normally run. Check if merging the command lines into a single one works for you and whether it does speed up the process. If it does then we can adjust autorandr to allow configuring using a single command, too..

I couldn't find how to disable autrandr automation, but I tried your dry run suggestion anyway, and it outputs:
`xrandr --fb 1920x2160 --output HDMI-1 --gamma 1.0:0.909:0.833 --mode 1920x1080 --pos 0x0 --primary --rate 60.00 --reflect normal --rotate normal --output eDP-1 --gamma 1.0:0.909:0.833 --mode 1920x1080 --pos 0x1080 --rate 59.98 --reflect normal --rotate normal`
(and it doesn't modify the active configuration, which is expected behaviour for a dry run)

I don't understand what you mean by putting all commands into a single line; my command _is_ a single `autorandr work`. Do you mean the disabling (and re-enabling) of the gnome and autorandr automation?

**Comment by phillipberndt** [comment]
If it's already only one command then there's nothing we can improve. Thanks for checking!
