### ISSUE TITLE
1.8.1 version fails on Ubuntu Eoan

### ISSUE THREAD

**Issue by SwampFalc** [phillipberndt/autorandr#187]
Hello,

Earlier today I upgraded my Ubuntu machine from Disco to Eoan.

This also caused an upgrade of autorandr, from 1.7 to 1.8.1.

Autorandr is now not working anymore:

    $ autorandr --config
    Invalid MIT-MAGIC-COOKIE-1 keyCan't open display :0
    Failed to run xrandr (line 479; /usr/local/lib/python2.7/dist-packages/autorandr.py)

I've already restarted my machine at least once.

**Comment by RasmusWL** [comment]
Hi @SwampFalc. Could you give some more details on your system?

What is the output of `xrandr --verbose`?

**Comment by fidergo-stephane-gourichon** [comment]
Hi! I'm using autorandr on Xubuntu 19.10 Eoan. It works, not perfectly, but it works for me. Not observed this.

@SwampFalc If you run another program, like `xmessage foo` or any program that is a X client, do you observe the same error or does it work?

**Comment by SwampFalc** [comment]
My system is a Lenovo laptop, running Ubuntu Eoan. Sitting in a Lenovo docking station with the lid closed, but connected to two external monitors.

`xrandr --verbose` output: https://gist.github.com/SwampFalc/c5d94deef57644d0fe1855549cf4d5b5

Also, `xmessage foo` works perfectly.


Hold on... `autorandr --version` just told me "1.7"... That's not normal. Might have made a mess of things between pip and apt. I'll check.

**Comment by SwampFalc** [comment]
Okay, yes! I had installed it through pip, not through apt. So it had not been updated at all. I'm now well and truly on 1.8.1 and it works at first sight.
