### ISSUE TITLE
[question] Auto-matching order

### ISSUE THREAD

**Issue by bbaserdem** [phillipberndt/autorandr#189]
I'm trying to understand how the detection in `--change` flag works. I have a couple config options; some of them are more generic; such as being docked at home vs some random output at display port;

```
cat Laptop-DockedAtHome/setup
DisplayPort-0 <Some specific EDID here>
```
```
cat Laptop-DP/setup
DisplayPort-0 *
```

Which one would take precedence?

I could not find any info on how one config takes precedence over the other in the docs (both the README page and the manual.)

**Comment by phillipberndt** [comment]
There's no special precedence rules for wildcards, but adding them would make sense, agreed. (Prefer the profile with the least amount of characters caught by the asterisk?)

So currently, the matching profile which has most recently been loaded will be applied.

**Comment by phillipberndt** [comment]
> There's no special precedence rules for wildcards, but adding them would make sense, agreed. (Prefer the profile with the least amount of characters caught by the asterisk?)

Implemented that. The profile with the best match now comes first.

**Comment by bbaserdem** [comment]
Thank you for the swift response. This is exactly what would be needed for my workflow.
