### ISSUE TITLE
Failed to parse Xrandr output

### ISSUE THREAD

**Issue by janhieber** [phillipberndt/autorandr#19]
Error message when calling autorandr:
Failed to parse current configuration from XRandR:
Parsing XRandR output failed, 3826 bytes left unmatched after regular expression,starting with ..'x1050 (0xb'.

xrandr -q --verbose: http://pastebin.com/x25Amtmi

System: Fujitsu Lifebook E Series, Ubuntu 14.10 64bit, dockingstation, two Screens connected at dock (DVI, VGA)

**Comment by phillipberndt** [comment]
The `1680` was accidentally parsed as a part of the EDID. I changed the regexp to require the two tabs in front of each EDID line. This should fix the problem.

**Comment by janhieber** [comment]
Wow, that was lightning fast. Thank you :)

Am 17. Februar 2015 10:53:47 MEZ, schrieb Phillip Berndt <notifications@github.com>:
>The `1680` was accidentally parsed as a part of the EDID. I changed the
>regexp to require the two tabs in front of each EDID line. This should
>fix the problem.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/phillipberndt/autorandr/issues/19#issuecomment-74642449

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
