### ISSUE TITLE
autorandr-launcher is blocking X11 session by default

### ISSUE THREAD

**Issue by dvzrv** [phillipberndt/autorandr#199]
After packaging 1.10, I got [this downstream ticket](https://bugs.archlinux.org/task/66419).
The XDG startup file basically blocks the X11 session by not calling `autorandr-launcher` with `--daemonize`.
Apart from that it seems the executable is segfaulting on session exit.

I'm currently more inclined to remove the new executable, as in comparison to the udev/systemd setup it still proves to be very fragile.
Additionally, I don't believe it is a great idea to install autostart files by default.

**Comment by fuzzysloth** [comment]
Got these messages in system journal:
`gnome-session-binary[3971]: WARNING: Application 'autorandr-launcher.desktop' killed by signal 11
systemd-coredump[4196]: Process 4041 (autorandr-launc) of user 1000 dumped core.
                                                         
                                                         Stack trace of thread 4041:
                                                         #0  0x000056454eed7257 n/a (autorandr-launcher + 0x1257)
                                                         #1  0x00007fa9bbdbf023 __libc_start_main (libc.so.6 + 0x27023)
                                                         #2  0x000056454eed73be n/a (autorandr-launcher + 0x13be)
`

Sorry, symbols were stripped from autorandr-launcher.

**Comment by phillipberndt** [comment]
Yes, at this point I'm also tempted to do a point release reverting to the old default.

I'm travelling until Sunday, I'll have a quick look then and will likely go with the revert.

**Comment by phillipberndt** [comment]
I'll do a patch release with this change reverted, see #195. And will fix the desktop file.

**Comment by fuzzysloth** [comment]
Thanks for the patch! I'll test it as soon as I get the updated package.
