### ISSUE TITLE
addition to README needed!!

### ISSUE THREAD

**Issue by johnmendrake** [phillipberndt/autorandr#200]
Sorry if this is the wrong place to state this, but I wanted to draw attention to it, that the README might need an update, considering the change from udev/systemd to autorandr-launcher.

For me it took a while to figure out why my system suddenly isn't changing the monitors automatically anymore, relying on me to execute `autorandr -c` manually every time. Would be nice to point it out in the description that the daemon must be started ;)

Greetings!

**Comment by phillipberndt** [comment]
I'll do a patch release with this change reverted, see #195.
