### ISSUE TITLE
Greys turn brown when switching profiles

### ISSUE THREAD

**Issue by glitchcrab** [phillipberndt/autorandr#201]
Yes, the subject sounds bizarre but then my issue is also quite bizarre.

I switch between two profiles (infrequently) - one is just the laptop by itself, and the other is the laptop plus dual external displays connected by HDMI/DP to the internal GPU (the nvidia card is disabled).

When autorandr switches layouts from the laptop to the desk profile it causes all sorts of weirdness to happen with the greyish blue colour I use for terminal and polybar backgrounds - they turn brown, but all other colours (such as my bash PS1) are unaffected. Sometimes switching profiles back fixes it, but sometimes not. The only guaranteed way to sort it is to end my i3 session and log in again (I use lightdm if that makes a difference). What's even more strange is that if I then reboot then the systemd shutdown text is also brown.

If I manually run xrandr to change the layout then I have no colour issues at all.

I appreciate that this is highly weird and possibly a snowflake issue with my laptop, but I'd appreciate it if you can shed any light on this at all!

**Comment by glitchcrab** [comment]
i'm not sure if it's relevant, but I also run redshift which obviously does stuff with gamma ramping - I can't imagine it's due to that but i'm clutching at straws at this point.

**Comment by phillipberndt** [comment]
Redshift is super relevant, since it uses gamma settings ramps that are more complex than what xrandr supports. There's an old issue somewhere around, try searching for it. I'd rather manually fix the gamma settings presave/postswitch, or skip gamma altogether (there's an autorandr option for skipping xrandr options)

**Comment by glitchcrab** [comment]
OK, I've skipped gamma for now and I'll see how I get on - I'll close this for now and re-open if necessary later. Thanks!
