### ISSUE TITLE
Support ignored monitors [idea]

### ISSUE THREAD

**Issue by seqizz** [phillipberndt/autorandr#202]
Hi,

First of all, thanks for maintaining this project.

I've realized a confusion while setting up. Here is my very similar 2 configs, which is currently working:

First one:
```
output DP3-1
pos 1920x0
mode 1920x1200
rate 59.95

output DP3-2
pos 0x0
mode 1920x1200
rate 59.95

output eDP1
off
```
Second:
```
output DP3-1
pos 1920x0
mode 1920x1200
rate 59.95

output DP3-2
pos 0x0
mode 1920x1200
rate 59.95
```

Confusion is, it detects first config when I open the lid, and second config when I close. I had to define like this, otherwise I have to ensure the position of the lid while booting/docking the system.

It might be easier if autorandr can support an option which indicates a monitor is not going to be used, regardless of it is detected or not. Something like:

```
output eDP1
ignore-output
off
```

Sorry if this is a duplicate, or can be already achieved somehow (maybe giving the "output eDP1" into skip options etc :\ ) but I couldn't manage to do it so wanted to mention.
Searching in the issues I can only see #104 , which is somewhat similar but can be painful to actually detect the state.

Thanks again :peace_symbol:

**Comment by phillipberndt** [comment]
If a lid is closed, autorandr considers eDP1 as disconnected.

What you posted here is the `config` (set of xrandr parameters). To decide which config to load, autorandr uses the `setup` file. Check if eDP1 is listed for the wrong configuration!

**Comment by seqizz** [comment]
There is no difference visible the setup files (checked with `diff`), both has same fingerprints from all monitors. Yet if I run `autorandr`, (detected) mark switches to the lid-off or lid-on version depending to the `config`s above.

**Comment by chall8908** [comment]
I'm having a related problem to this.  Now that lid state affects the "connected" or "disconnected" state of the internal monitor, I have an issue where I require multiple configurations to detect my actual setup.  For my purposes, I don't care if the lid is open or closed, I always want the internal monitor disabled if an external is plugged in.  And, yes, I sometimes do have the lid open if I'm doing something quick and don't want to swap to my keyboard around.

Being able to configure autorandr such that it ignores the "connected" or "disconnected" state of, at least, a built-in monitor would eliminate my need for a workaround.
