### ISSUE TITLE
Unpair device => select parent receiver?

### ISSUE THREAD

**Issue by Noughtnaut** [phillipberndt/autorandr#231]
I find that, of the times where I'm fiddling with Solaar, I often have the need to unpair and re-pair a device. Mind you, not because of a software problem, but perhaps I've brought a paired mouse with me somewhere else and the mouse then needs to be re-paired when I get back.

In those cases, it would be a tiny convenience if unpairing a device would mean that its receiver would be selected in the device list, rather than (as now) whatever random other device might be listed right above the newly unpaired device.

I really hope this is a 5-minute job, [otherwise](https://xkcd.com/1205/) I suppose I'll manage to make one whole extra mouse click myself.

**Comment by phillipberndt** [comment]
I'm afraid I don't get this request. Could it be you filed it against the wrong repository?

**Comment by Noughtnaut** [comment]
Why, yes I am! :D Guess who's tired...

This was intended for the [Solaar](https://github.com/pwr-Solaar/Solaar) project, also on github. Thank you for your impressive response time.
