### ISSUE TITLE
autorandr-lid-listener.service is not installed

### ISSUE THREAD

**Issue by DeltaWhy** [phillipberndt/autorandr#234]
I am using the Arch Linux package of autorandr and the layout does not switch automatically when closing/opening the laptop lid. It appears the `autorandr-lid-listener.service` does not get installed by the Makefile and so is not packaged either.

This could be fixed by manually copying the file in the packaging script but it seems more reasonable for the Makefile to install it along with the other systemd service.

**Comment by itzmanish** [comment]
is there any script available for autorandr?

**Comment by toddnni** [comment]
Yes, there is the script in this repo
<https://github.com/phillipberndt/autorandr/blob/master/contrib/systemd/autorandr-lid-listener.service>

Packaging would be great. Let's do a PR (if we remember to).
