### ISSUE TITLE
Any documentation on how to use /etc/xdg/autorandr

### ISSUE THREAD

**Issue by jdillon** [phillipberndt/autorandr#246]
I was trying to see if I could use autorandr to setup the display configuration for KDE SDDM when my system starts so that it has the proper displays in the correct orientation.  I am not really sure though if it can do this or not and/or if maybe the `/etc/xdg/autorandr` is meant to be used for this purpose?  I couldn't find any information about how to use the "system wide configuration" though.

I was able to use autorandr to capture a profile as the user i'm logged in as, and then use `autorandr --force --dry-run default` to spit out the xrandr commands; and if I append that output to `/usr/share/sddm/scripts/Xsetup` it behaves as I want.

But I am wondering if i'm just missing how the system wide configuration is meant to work and/or if there is an easier way to do this?

**Comment by phillipberndt** [comment]
Configurations right now are per-user. System wide installation only means that autorandr will run for everyone.

**Comment by jdillon** [comment]
@phillipberndt thx for the clarification
