### ISSUE TITLE
Alternative autorandr packaging on AUR

### ISSUE THREAD

**Issue by atreyasha** [phillipberndt/autorandr#250]
Hi, thanks for your great work here. I have some questions regarding the packaging of `autorandr`.

For my use case, I want to have the `autorandr` script installed on my system without any of the `systemd` or `udev` hooks for automatic monitor refreshing. AFAIK, the only way to do this now is via `pip`. However, I want all of my system packages to be tracked by my package manager, which is a wrapper of `pacman` on Arch Linux.

To achieve this, I am thinking of creating an [AUR](https://aur.archlinux.org/) package and naming it `autorandr-nohooks`. Below are my questions:

1. Is the naming of this package appropriate, or should it be something like `autorandr-script`?
2. Is there a possibility of using `make install` with additional arguments to install `autorandr` without the aforementioned hooks, but keeping nice features like the shell autocompletions?
3. Would you be interested in adding a link to this package in the readme, when I eventually release it on the AUR?

**Comment by phillipberndt** [comment]
Hi,

1. I don't think I should interfere with that. Naming schemes are up to distributions. If as a user you feel this is the right name for the package, go for it.
2. Yes, the makefile already has several targets; it uses auto-detection to decide the defaults, but you can override that.
3. Sure thing.

One further thought, doesn't pacman have some mechanism to configure this? I don't have experience with it, but I'm thinking either upfront like Gentoo's USE flags, or after installation like Debian's defaults/alternatives/divert mechanisms.

**Comment by atreyasha** [comment]
Thanks for the responses.

> One further thought, doesn't pacman have some mechanism to configure this?

AFAIK, this is not possible if you use the upstream package. `pacman` requires a special file called `PKGBUILD` to configure the installation process. For example, the `PKGBUILD` for `autorandr` can be found [here](https://github.com/archlinux/svntogit-community/blob/packages/autorandr/trunk/PKGBUILD). As seen, the default `make install` command is used.

Will close this issue and write back when I have the package ready.
