### ISSUE TITLE
Differences in gamma value

### ISSUE THREAD

**Issue by blueyed** [phillipberndt/autorandr#26]
I've noticed that a setup is not being detected as active already, because
of a difference in the `--gamma` value (the last number):

    {'DP1': <DP1 --output DP1 --off>,
     'DP2': <DP2 --output DP2 --off>,
     'DP3': <DP3 --output DP3 --off>,
     'HDMI1': <HDMI1 00fff..000ee --output HDMI1 --gamma 1.0:1.1:1.2 --mode 1920x1080 --panning 0x0 --pos 1366x0 --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1>,
     'HDMI2': <HDMI2 --output HDMI2 --off>,
     'HDMI3': <HDMI3 --output HDMI3 --off>,
     'LVDS1': <LVDS1 00fff..30059 --output LVDS1 --gamma 1.0:1.1:1.2 --mode 1366x768 --panning 0x0 --pos 0x312 --primary --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1>,
     'VGA1': <VGA1 --output VGA1 --off>,
     'VIRTUAL1': <VIRTUAL1 --output VIRTUAL1 --off>}

    {'DP1': <DP1 --output DP1 --off>,
     'DP2': <DP2 --output DP2 --off>,
     'DP3': <DP3 --output DP3 --off>,
     'HDMI1': <HDMI1 00fff..000ee --output HDMI1 --gamma 1.0:1.2:1.3 --mode 1920x1080 --panning 0x0 --pos 1366x0 --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1>,
     'HDMI2': <HDMI2 --output HDMI2 --off>,
     'HDMI3': <HDMI3 --output HDMI3 --off>,
     'LVDS1': <LVDS1 00fff..30059 --output LVDS1 --gamma 1.0:1.2:1.3 --mode 1366x768 --panning 0x0 --pos 0x312 --primary --rate 60.0 --reflect normal --rotate normal --transform 1,0,0,0,1,0,0,0,1>,
     'VGA1': <VGA1 --output VGA1 --off>,
     'VIRTUAL1': <VIRTUAL1 --output VIRTUAL1 --off>}

I am not sure what might have changed this?

Maybe this could be considered irrelevant? (if we figure out / it turns out that it's nothing that was set explicitly)

For now, I've resaved it.

**Comment by phillipberndt** [comment]
I don't see how one could detect whether a change in `--gamma` was intentional. Always ignoring the `--gamma` value doesn't work either, because some users might use this intentionally.

Why is it important to you to correctly detect this? (I guess some `postswitch` script is in place? Would it help to report what changed to the script?)

The other thing I can think of is to give `autorandr` an option to generally ignore certain xrandr options, e.g.

    autorandr -c --skip-options "gamma"

**Comment by blueyed** [comment]
My main issue here was that autorandr did not detect it as the same setup, although I've not (intentionally) changed it.

I am currently in the process of migrating away from gnome-settings-daemon, using awesomeWM as window manager - this might have influenced it.

At first, I thought that it was maybe some incremental counter - but currently it appears to stick.

**Comment by blueyed** [comment]
I think this gamma difference comes from using [redshift](https://github.com/jonls/redshift).

So for me a `--skip-options` argument would be necessary.

**Comment by blueyed** [comment]
@phillipberndt 
I've tested your branch/commit: it works as expected.
Thanks!

**Comment by blueyed** [comment]
Now it would be nice, if the system script (pm-utils/40autorandr) would read some config file (/etc/default/autorandr.conf) or something similar to allow for adjusting the command to be run:

    AUTORANDR="autorandr -c --default default"

**Comment by phillipberndt** [comment]
Great. I pulled this to master now.
