### ISSUE TITLE
User IDs starting below 1000.

### ISSUE THREAD

**Issue by elderK** [phillipberndt/autorandr#262]
Hey there,

I just thought I'd let you know that there's a distribution in the wild that starts new User IDs at 100. :)

The distribution in question is Crux, which I use.

The issue I hit was that automatic profile switching with udev would fail unless I updated the "minimium UID check" in autorandr.

I'm not sure what the best fix for this would be. As you mention in the source, there doesn't seem to be a single source of truth for what the minimum UID actually is.

**Comment by utf8please** [comment]
+1 on this. I have my UID set to 501 and batch mode does nothing for me. While I agree there is no single good solution, can we make this configurable instead? Even something as simple as parsing a env var (say `AUTORANDR_MIN_UID`) can unblock this.

I'm happy to send a PR if we can agree on a solution :)

**Comment by phillipberndt** [comment]
I wonder if checking for valid homes and shells and whether the account is active would be too much?!

No concerns around the environment variable idea if it helps though.

**Comment by utf8please** [comment]
All right, my attempt at environment variable is at #288.
