### ISSUE TITLE
Autorandr and Global Environments Variables

### ISSUE THREAD

**Issue by TheTrveAnthony** [phillipberndt/autorandr#263]
Hi there,

BSPWM user here. I use autorandr to autodetect when an HDMI monitor gets unplugged to come back to "normal mode" (eDP-1 only if you will). I initially wrote all my scripts with local variables and everything worked perfectly fine. Yesterday I changed local variables to global environments variables to make everything easier to manage, so I went from  (not my script, just a tiny example): 

```
#/bin/sh

# local variables
main = 'eDP-1'
aux = 'HDMI-1'

#### do whatever ....
bspc monitor $main -a desk
bspc desktop desk --to-monitor $aux
```

to this :

```
#/bin/sh

# no more local vars, we use global variables instead

#### do whatever ....
bspc monitor $MNTR0 -a desk
bspc desktop desk --to-monitor $MNTR1
```

And now the unplug script doesn't run as expected. After a few investigations, I found out that it does everything as it should when I run it manually, which means that autorandr seems to be unable to read global variables (Does it run in some kind of isolated environment ?). Is there a way to solve this or do I have to stick with local variables ? I did read about the AUTORANDR_ variables but I have no idea how they work and how to use them.

Also, I use fish, and my global variables are defined in my config.fish as follows : 
```
set -gx MNTR0 'eDP-1'
set -gx MNTR1 'HDMI-1'
```

Thank you for whoever shall answer and thanks for this amazing piece of software !! \m/

**Comment by phillipberndt** [comment]
How to you run autorandr? If it's not from a shell or process in your x11 but via systemd, then you won't have your environment variables.

You could e.g. explicitly `source` your shell's rc file at the top of your script to work around that, or change the sheband at the top to run the script in a login shell if your shell supports that.

**Comment by TheTrveAnthony** [comment]
Hi,

Thanks for your quick response.
Indeed I run autorandr via systemd, as you suggested I simply added ```. $HOME/variables.sh``` in postswitch and it runs perfectly now, thanks !!

**Comment by phillipberndt** [comment]
>  Quick question : Does it happen with other inits as well ? (OpenRC and Runit in particular)

There's a more generic answer. Any process you launch will inherit it's parent processes environment variables. And if you spawn an interactive shell, it will process your profile/rc scripts that set custom environment variables.

Since the init system never is a child process of an interactive shell owned by your user, it will never have your environment variables set.
