### ISSUE TITLE
DeprecationWarning: The distutils package is deprecated with Python 3.10

### ISSUE THREAD

**Issue by pkotvan** [phillipberndt/autorandr#266]
Hi,

There is a deprecation warning with Python 3.10 when running autorandr.

/usr/bin/autorandr:42: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
`  from distutils.version import LooseVersion as Version`

**Comment by pkotvan** [comment]
I looked around a bit and it should be possible to replace distutils.version with packaging.version but it's not a drop-in replacement. Some code changes will be necessary. I will check it out and try to provide a pull request with packaging instead of distutils.

**Comment by pkotvan** [comment]
According to [Porting from Distutils](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html?highlight=distutils%20package%20is%20deprecated%20and%20slated%20for%20removal%20in%20python%203.12) `distutils.version.*` can be replaced  by `packaging.version.*`. This however might not be that straightforward since autorandr is using `distutils.version.Looseversion` which is:
> Version numbering for anarchists and software realists.

On the other hand, `packaging.version.*` follows [PEP-440](https://www.python.org/dev/peps/pep-0440/).

I tried to simply replace the distutils with packaging and it seems to work. [pr#267](https://github.com/phillipberndt/autorandr/pull/267)

**Comment by pkotvan** [comment]
@phillipberndt Do you have any idea whether such a change is desired?

**Comment by pkotvan** [comment]
Well. This may be problematic as `Version` is used to compare versions xrandr parsed from `xrandr -v`. It works. But it depends on the fact that xrandr versioning follows the specification.

**Comment by phillipberndt** [comment]
I don't think that's a big problem (for now). Thanks for the PR, left a comment.

**Comment by elQuero93** [comment]
HI, on my ArchLinux installation Python got updated to 3.10 and now I can't run autorandr anymore. It stops at the deprecation warning message:

```
λ autorandr --detect
/sbin/autorandr:42: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion as Version
```

I can't downgrade to Python 3.10 because it requires to downgrade a lot of other packages. Could be done anything else in order to mitigate this issue?

**Comment by pkotvan** [comment]
@elQuero93, so far it's just a deprecation warning. It should work fine it will just print this message when you run it. As the message says, the distutils package will be removed in python 3.12.

The change in #267 should fix the issue.

**Comment by pkotvan** [comment]
@phillipberndt , do you plan to create a new release anytime soon?

**Comment by phillipberndt** [comment]
Releases don't follow a schedule, and I keep forgetting to unless reminded. Thanks! I have some time Thursday, will do a release then.

**Comment by phillipberndt** [comment]
Released a bunch of things, including this change, as 1.12.

**Comment by rixx** [comment]
I'm still seeing this warning on 1.12:

```shell
autorandr --version
/usr/bin/autorandr:49: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion as Version
autorandr 1.12.1
```

**Comment by AgereJoseph1** [comment]
I am also seeing the same problem

**Comment by yoarch** [comment]
I have the same issue with python 3.10. Downgrading to older python version to get autorandr working back.

**Comment by phillipberndt** [comment]
Is it actually broken for you or is this about the deprecation message?

**Comment by yoarch** [comment]
Actually broken. Showing the deprecated message with no other output.

**Comment by techwithvisal** [comment]
I also just faced this issue too within these 3 days.

**Comment by jezcope** [comment]
FYI `packaging` is not in the Python standard library like `distutils` is: https://pypi.org/project/packaging/. It'll need to be added as a dependency to this package to avoid breakage on Python 3.12, and anyone who hasn't installed it separately will continue to see the deprecation warning on Python >= 3.10.

The Python 3.10 changelog also offers making your own copy of the relevant code as a solution, if you want to avoid the dependency. https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated

**Comment by xss** [comment]
Is there a reason why this message must be shown all the time, even though the alternatives *are* already installed and available? Can this be suppressed? This is so confusing... autorandr seems to currently work (again), however.

**Comment by TasbasMN** [comment]
still persists

OS: Ubuntu 22.04.4 LTS x86_64

nazif@nazo:~$ autorandr
/usr/bin/autorandr:42: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion as Version

nazif@nazo:~$ python3 --version
Python 3.10.12
