### ISSUE TITLE
Handling unstable video output names

### ISSUE THREAD

**Issue by ginkel** [phillipberndt/autorandr#271]
Hi there,

thanks for maintaining autorandr! I am currently struggling with the following problem: The video output names on my Lenovo Thunderbolt dock do not seem to be stable. The DP output named DP1-2 may be named DP2-2 after a reboot. Is there a way to accommodate this behavior in autorandr, i.e. handle the output named `DP*` in both `setup` and `config`?

Thanks,
Thilo

**Comment by ginkel** [comment]
AFAICS https://github.com/phillipberndt/autorandr/pull/248 seems to offer a solution for this...

**Comment by phillipberndt** [comment]
Merged that PR
