### ISSUE TITLE
Specify match-edid from the user's configuration

### ISSUE THREAD

**Issue by aviau** [phillipberndt/autorandr#274]
Hello,

Would there be a way to specify `--match-edid` in my user configuration?

Right now, in Debian, when a monitor is plugged in, we have a udev rule that runs `/bin/systemctl start --no-block autorandr.service`.

Which will in turn run `/usr/bin/autorandr --batch --change --default default`.

Now I am wondering if we should:
- Change the sytemd unit to include `--match-edid`. (could be a breaking change for some users, and it could also create conflicts in situation where one user of the sytem wants the option and the other does not)
- Find a way for users to add `match_edid = True` or similar somewhere in their user configuration. (ex: `~/.config/autorandr/options`)
- Set this per-profile?

**Comment by phillipberndt** [comment]
`settings.ini` should work as expected for per-user defaults.

Per-profile, my preferred approach would have been the patch I've had posted in a ticket some time ago, where the actual name of the output is replaced with `x-edid-match` in the configuration file, or something similar. But if there's at least one user with a use case, I'm not opposed to adding another file, either..

I wouldn't want to make this the default choice. For most users that'd enable this flag, it is a workaround for a bug, after all..

**Comment by aviau** [comment]
Ah, I missed `settings.ini`. It works fine for most use cases I think.

Maybe `settings.ini` should be mentioned in the manpage?

**Comment by phillipberndt** [comment]
Sure, that'd be great. Manpage and README aren't in sync right now, and there's probably still entirely undocumented features..

If you find the time, feel free to open a PR!

**Comment by aviau** [comment]
> If you find the time, feel free to open a PR!

Will do. Added to my todo list :)
