### ISSUE TITLE
Support for systemd

### ISSUE THREAD

**Issue by blueyed** [phillipberndt/autorandr#29]
systemd does not use pm-utils, so autorandr is not being run after resuming.

The following could be installed into /etc/systemd/system/autorandr-resume.service:

    [Unit]
    Description=autorandr resume hook
    After=sleep.target

    [Service]
    ExecStart=/etc/pm/sleep.d/40autorandr thaw

    [Install]
    WantedBy=sleep.target

It would also be possible to use the user's systemd instance instead, but
that part seems to in flux currently, with regard to having $DISPLAY and $XAUTHORITY available in there (https://wiki.archlinux.org/index.php/Systemd/User#Environment_variables).

**Comment by blueyed** [comment]
Would it be preferred to use the user's systemd instance (via the user's config), or is it meant to be installed system-wide?

(When installing it system-wide, it could also be put into `/etc/systemd/user` though (as a user service, for all users).

**Comment by blueyed** [comment]
An alternative might be to install a script/symlink into `/usr/lib/systemd/system-sleep` (https://wiki.archlinux.org/index.php/Power_management#Hooks_in_.2Fusr.2Flib.2Fsystemd.2Fsystem-sleep), running autoranrd when the "post" argument is used.

**Comment by phillipberndt** [comment]
I use autorandr from my user home and frankly never put too much thought into this.. just go ahead and create a pull request with your start scripts, I'll merge it.

*However* I'd like to organize the additional scripts/files a bit better. How about moving
* bash_completion -> contrib/bash_completion
* pm-utils -> contrib/pm-utils
* udev -> contrib/udev
* your systemd stuff -> contrib/systemd

and adjusting the makefile to auto-detect the system type and adjust the hotplug-target accordingly?!

**Comment by blueyed** [comment]
:+1:

**Comment by blueyed** [comment]
> I use autorandr from my user home

Are you using udev rules then?  AFAIK these cannot be configured in local/user config?
(but you can call a user's script of course)

**Comment by phillipberndt** [comment]
I have my own udev rule in place, that calls a script from my home, just not the one from the repo ☺

**Comment by kepi** [comment]
:+1:

**Comment by phillipberndt** [comment]
I've included the service file from this bug now.

**Comment by Konfekt** [comment]
Just curious why there is no
```
After=sleep.target suspend.target
```
? Does sleep.target include the suspend.target?
