### ISSUE TITLE
autorandr miscalculates fb with fractional scaling < 1

### ISSUE THREAD

**Issue by mafheldt** [phillipberndt/autorandr#296]
setup is Xubuntu 20.4, autorandr 1.8.1, 43" 4k monitor flanked by 2 24" 2k monitors
the transform scale is .787963,0,0,0,.787963,0,0,0,1 on the 43" monitor only (a sop to my aging eyes)

(I'm afraid Python is not one of the 2/3 dozen languages I have used in the last 50+ years (gasp - horror!), so I may not have the problems properly defined, nor the solutions correct, but... )

Two issues
a) My understanding (comments) is that because of an xrandr bug, autorandr attempts to disable the existing transform on my monitor. It  fails because it sets the fb to the size of the transformed screen. Naturally that is too small when the scale is < 1.

b) In calculating the fb size for the transform it returns the int(height) instead of math.ceil(height) which causes the fb to generally be 1 pixel too small for non-integer scaling

My suggested possible solutions (which work on my system - so I'm sure they will work on any system -**choke** **choke**)

a) in the function apply_configuration, I moved the code that calls get_fb_dimensions from the beginning of the function to after "auxiliary_changes_pre" are done. That way there is no fb set for either disabling panning or transforming, by delaying the addition of the --fb arg to base_argv.

b) I added import math and changed the return stmt of get_fb_dimensions to
 return math.ceil(width), math.ceil(height)

I will note (and my carefully selected scale factor is an example) that xrandr seems to lose the least significant bit of the single precision representation of the scale factor hence math.ciel(s) will return a fb one larger that xrandr would have chosen. As this depends on the peculiarities (current and future) of xrandr, the only complete solution would be to then re-read the configuration and adjust the fb size - perhaps overly anal.

**Comment by phillipberndt** [comment]
Thanks! (b) sounds simpler, so I went with that for now until someone complains :wink:

**Comment by mafheldt** [comment]
Phillip,

Sorry if I didn't make myself clear, but both (a) and (b) are necessary.
(b) fixes the "off by 1" problem that occurs if there is a fractional scale
factor.
(a) fixes the problem if there the scale is <1

Autorandr attempts to disable all scaling ( xrandr --output ZZZ --fb XxY
--transpose off) at the start.
Because the fb size is calculated including the final scale factor XxY is
too small for the unscaled output.
By moving the code as suggested the disabling of scaling and panning is
done without an explicit fb size.
The rest of the xrandr commands (after "auxiliary_changes_pre") are then
done as before with the calculated fb size.

This works for me, but I have a different problem (my configuration is more
complicated than described) where xrandr seg faults leaving the display
system in a strange state.
I haven't yet figured out exactly why, or quite how to get out of the
state, but I am quite sure it is not autorandr's fault and just another
"undocumented feature" of xrandr!
I will submit a change request if I ever figure it out
Thanks
mike

**Comment by phillipberndt** [comment]
I see.

**Comment by phillipberndt** [comment]
I spent some time toying with a better solution, and yes, it's not nice. Going to go with your proposal until someone complains :)
