### ISSUE TITLE
1.13 release

### ISSUE THREAD

**Issue by GaetanLepage** [phillipberndt/autorandr#317]
Hello !
Thank you for developing this very convenient software !

I was wondering when the `1.13` (or `1.12.2`) version would be released.
It has been a full year since `1.12.1` and since then, some things have changed.
For instance, the `--ignore-lid` flag seems very practical.

Is there some kind of TODO list of features/bug to tackle before a release can be considered ?

Thank you in advance for any information :)

**Comment by phillipberndt** [comment]
I had taken an TODO entry for the release and then forgotten about it :facepalm: Released now!

**Comment by perrin4869** [comment]
@phillipberndt Thanks for the release!
It would be extremely useful for us package maintainers (I maintain the SlackBuild for autorandr) if you could make a release inside the `Releases` tab it github as well, that way I can get a notification each time you release, and I can update the package.
Thanks again!

**Comment by phillipberndt** [comment]
Thanks! I thought tagging it was enough for everyone. Done now, and I'll create releases from the tags going forward.

**Comment by perrin4869** [comment]
That'll be incredibly helpful! Thanks!
