### ISSUE TITLE
Kinda fixed a problem with transform and --fb

### ISSUE THREAD

**Issue by Gerstensaft** [phillipberndt/autorandr#319]
Yea Hi,
I am quite new here and this is my first post. Pls have mercy if I am in the wrong place. 
I noticed, if the scale/transform option is used in xrandr, the screen gets scaled correctly without error. But the --fb will not adjust. After a night of work I found out, its not a specific Problem of autorandr instead of xrandr BUT autorandr can provide an easy workaround. When for example using this example command: "xrandr --fb 5232x1440 --output HDMI-0 --mode 3440x1440 --pos 0x0 --output eDP-1-1 --mode 2560x1440 --pos 3440x0 --transform 0.7,0,0,0,0.7,0,0,0,1" the fb gets not set correctly which results in a screen that "scrolls" like a tactical map in a video game, since the fb ignores scaling and is bigger than the virtual screen. This can be worked around with a second command "xrandr --fb 5232x1440" afterwards. Then the fb is set correctly and the screen does not "scroll" anymore. So at the end of "apply_configuration" function i added:
fb_string = ""
for f in fb_args:
    fb_string += f + " "
print(fb_string)
os.system("xrandr " + fb_string)

With this code snipped, the fb gets set correctly separately after the main command is executed. I have to add that i use a 2 monitor setup. I dont know if the problem cam be reproduced while scaling only a single screen. The default fb value of xrandr might prevent this problem in single monitor setups. I dont know.

Hope i could help. Write if questions occur.

**Comment by phillipberndt** [comment]
Thanks! Included that code in 9aa18d7bd948400a8b35b3078b979fd4b2f18fd7, will release shortly.
