### ISSUE TITLE
autorandr runs default profile postscript twice on startup

### ISSUE THREAD

**Issue by ByteDrummer** [phillipberndt/autorandr#323]
autorandr version is `1.13.2`

autorandr runs the default profile postscript twice on startup, which sometimes launches polybar twice, seemingly due to a race condition. This is the relevant snippet that is executed to launch polybar:
```
#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

MONITOR=$(xrandr | grep primary | sed 's/ .*//') polybar --reload top &
```

**Comment by phillipberndt** [comment]
It should only do that if autorandr itself runs twice - can you figure out why that is? E.g. dump the process tree with all parents from the predetect hook.

**Comment by phillipberndt** [comment]
Maybe due to https://github.com/phillipberndt/autorandr/pull/320?

**Comment by ByteDrummer** [comment]
Oh yeah, that's what's causing it. Both `/etc/xdg/autostart/autorandr.desktop` and `autorandr.service` are launching autorandr. I just deleted the desktop file. Shouldn't one of these autostart methods be opt-in?

**Comment by phillipberndt** [comment]
The KDE one has a key that is supposed to make it KDE-only.. if that doesn't work then I guess so :(

**Comment by ByteDrummer** [comment]
I'm using `dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &` to launch startup programs. Maybe this is an issue with `dex` or it's because I don't have `XDG_CURRENT_DESKTOP` set. I tried adding `export XDG_CURRENT_DESKTOP=bspwm` in my `.zprofile` but that didn't help.

**Comment by ByteDrummer** [comment]
Oh, it looks like `dex` might not use `XDG_CURRENT_DESKTOP`, and instead, you need to provide it through `--environment bspwm` as an option.

Sorry for the spam.
