### ISSUE TITLE
Respond to udev `change` events?

### ISSUE THREAD

**Issue by LRitzdorf** [phillipberndt/autorandr#324]
On my Lenovo Legion laptop, (dis)connecting a monitor to/from my HDMI output generates a udev `change` event, instead of the expected `add` or `remove`. For example, connecting a monitor looks like this:
```sh
$ udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[401.262662] change   /devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0 (drm)
KERNEL[401.311233] change   /devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0 (drm)
UDEV  [404.389399] change   /devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0 (drm)
UDEV  [404.569207] change   /devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0 (drm)
^C
```

This causes the udev rule not to trigger, but can be fixed by using `ACTION=="add|remove|change"` in the udev rule, as opposed to just `ACTION=="add|remove"`.

Is there a particular reason that the current rule doesn't trigger on `change` events? Would you be willing to add this?

**Comment by phillipberndt** [comment]
See #321. Seems what fixes a bug for others causes one for you.. I'll revert that then.

**Comment by LRitzdorf** [comment]
Hm, that's strange. Thanks for the fix!
