### ISSUE TITLE
/etc/xdg/autorandr issue

### ISSUE THREAD

**Issue by aidenscott2016** [phillipberndt/autorandr#327]
Hello Phillip, thanks for your work on autorandr! 

I've found an issue, which may or not be a real issue.

I've just spent the morning working on a systemd user service which runs autorandr when I log in. I encountered a problem where if `XDG_CONFIG_DIRS` is set, then `autrorandr` will not check `/etc/xdg/autorandr` for profiles. I resolved this issue for myself by settings XDG_CONFIG_DIRS=/etc/xdg in my service definition. I think the responsible line is [this](https://github.com/phillipberndt/autorandr/blob/master/autorandr.py#L1213) where `/etc/xdg` is being used as a fallback only.

I understand that the xdg spec says :

> If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used. 

But the README states:

> /etc/xdg/autorandr for system wide configuration

Which I infer to mean that a system wide configuration is supported. The above statement does refer to hooks, not profiles, but I see that it uses the same [snippet](https://github.com/phillipberndt/autorandr/blob/master/autorandr.py#L1213) to check the `XDG_CONFIG_DIRS` envvar.

My issue here is that, although you don't explicitly state that a system wide install is supported, you can read the README and infer that it is. I think I would either explicitly join `/etc/xdg` to `XDG_CONFIG_DIRS` or state that system wide profiles are not supported.

Thanks for reading!

autorandr 1.13.3, nixos

**Comment by aidenscott2016** [comment]
systemd does seem to pass `XDG_CONFIG_DIRS` to `autorandr` as a user service, but for whatever reason without `/etc/xdg`

**Comment by phillipberndt** [comment]
That `XDG_CONFIG_DIRS` doesn't contain the default as a fallback is, for all I can see, an implementation detail of your OS, not hardcoded in systemd. You should be able to change that.

**Comment by aidenscott2016** [comment]
Yep I thought you might say that but I thought I should double check just in case. Maybe someone with the same problem will see this issue
