### ISSUE TITLE
postscript loses authentication for systemctl commands after suspending

### ISSUE THREAD

**Issue by ByteDrummer** [phillipberndt/autorandr#366]
For testing purposes, I'm relying on the following  postscript for the `common` profile symlinked to `default` which executes after logging in and resuming from suspend:
```
#!/bin/bash

echo "running postscript" >> ~/.config/autorandr/test.txt
systemctl suspend &>> ~/.config/autorandr/test.txt
```
When automatically executed after resuming from suspend, this script gives the following output:
```
running postscript
Call to Suspend failed: Interactive authentication required.
```
This is an issue because I use autorandr to run polybar, and polybar to open a rofi power menu with buttons that allow me to suspend, reboot, and power off my computer. Since the rofi power menu is a subprocess of the postscript, none of these menu buttons work because of the lack of permissions.

It's only an issue when the postscript is run automatically after suspending. Furthermore, if I manually execute `autorandr --load default` I don't encounter this permission issue.

**Comment by phillipberndt** [comment]
You can work around this by prefixing `systemctl suspend` with `sudo` and then allowlisting that command for `NOPASSWD` with `visudo`.

An alternative is to keep the session in the sudo authentication cache by periodically running `sudo -v`. I don't know if that survives suspend.
