### ISSUE TITLE
Broken regexes due to missing `r` string literal

### ISSUE THREAD

**Issue by lukasjuhrich** [phillipberndt/autorandr#368]
I upgraded to python 3.12 in a dev environment and ran `autorandr 1.14` in it (by accident). It reports:

```
/usr/bin/autorandr:210: SyntaxWarning: invalid escape sequence '\s'
  XRANDR_OUTPUT_REGEXP = """(?x)
/usr/bin/autorandr:236: SyntaxWarning: invalid escape sequence '\s'
  """ + XRANDR_PROPERTIES_REGEXP + """ |                                      # Properties to include in the profile
/usr/bin/autorandr:248: SyntaxWarning: invalid escape sequence '\S'
  XRANDR_OUTPUT_MODES_REGEXP = """(?x)
/usr/bin/autorandr:592: SyntaxWarning: invalid escape sequence '\s'
  version = re.search("xrandr program version\s+([0-9\.]+)", version_string).group(1)
/usr/bin/autorandr:888: SyntaxWarning: invalid escape sequence '\+'
  match = re.match("(?P<w>[0-9]+)x(?P<h>[0-9]+)(?:\+(?P<x>[0-9]+))?(?:\+(?P<y>[0-9]+))?.*", output.options["panning"])
```

In the current `master` branch, these issues seem to be still present:

https://github.com/phillipberndt/autorandr/blob/bb98da7e7336ab192bb0580a09c0b1a7c53d99ba/autorandr.py#L210-L246

https://github.com/phillipberndt/autorandr/blob/bb98da7e7336ab192bb0580a09c0b1a7c53d99ba/autorandr.py#L592

https://github.com/phillipberndt/autorandr/blob/bb98da7e7336ab192bb0580a09c0b1a7c53d99ba/autorandr.py#L888

**Comment by manuben13** [comment]
I have the same issue with autorandr 1.13.3 on Fedora 39 with Python 3.12

**Comment by phillipberndt** [comment]
I'm traveling right now and won't be able to make this change myself any time soon, but if you could open a PR I'll happily click merge!

**Comment by lukasjuhrich** [comment]
@phillipberndt done

**Comment by phillipberndt** [comment]
Thanks! Merged

**Comment by lukasjuhrich** [comment]
> @lukasjuhrich you forgot line 236. At least I got a SyntaxWarning for that as well. My PR should solve that but I also had to edit line 237 (turning `\\t` to `\t`).

Thank you for catching that. I recall running `ruff` but appearently forgot to enable the relevant check (`W605`)[https://docs.astral.sh/ruff/rules/invalid-escape-sequence/]. after your fix no invalid escape sequences are reported.
