### ISSUE TITLE
autorandr_monitor not working / inotify not supported for sysfs

### ISSUE THREAD

**Issue by blueyed** [phillipberndt/autorandr#41]
I've looked at the [autorandr_monitor](https://github.com/phillipberndt/autorandr/commit/43bb98c613862cdf8cb81a49a03b30f70c706816#diff-a642bcac274075d53e0bf2df1f415a11) script, but then found that inotify is not meant to work properly for sysfs, at least according to http://comments.gmane.org/gmane.linux.file-systems/83641.

While I see events in general, they seem to be delayed (a lot).

Does the script work for you?

**Comment by phillipberndt** [comment]
Frankly, I've never tried, but your objection sounds reasonable. I'll remove the tool, there's plenty of alternatives, e.g. https://github.com/nalipaz/poll-xrandr or http://portix.bitbucket.org/srandrd/.
