### ISSUE TITLE
/etc/pm/sleep.d/40autorandr fails with long user names

### ISSUE THREAD

**Issue by ValiValpas** [phillipberndt/autorandr#44]
This is because `w`, which is used in favour of `who`, only reports the first eight characters of the user names.

As I am not sure whether this is a general issue with `w` or related to my version, here is the `w --version` output:
```
w from procps-ng 3.3.11
```

**Comment by blueyed** [comment]
There would be `PROCPS_USERLEN`, according to `w(1)`.

**Comment by phillipberndt** [comment]
@ValiValpas, does the workaround @blueyed suggested work for you?

**Comment by ValiValpas** [comment]
@phillipberndt, yes that works for me.

**Comment by phillipberndt** [comment]
D'oh! I had the limits from PROCPS_FROMLEN in mind when I committed that. Fixed.
