### ISSUE TITLE
contrib/pm-utils/40autorandr should be installed always/mostly

### ISSUE THREAD

**Issue by blueyed** [phillipberndt/autorandr#45]
The Makefile will not install `contrib/pm-utils/40autorandr` in case `/usr/sbin/pm-suspend` does not exist, but it's used by the systemd and udev scripts, too.

Apart from that the script should maybe be moved to a more generic place, e.g. `/var/lib/autorandr` and then be used from there?!

**Comment by phillipberndt** [comment]
Sounds good to me, but [`/var` is the wrong place for this](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). How about `$PREFIX/share/autorandr`? (We'd have to replace the directory in the udev/systemd scripts on installation then, of course.)

**Comment by phillipberndt** [comment]
I just had the idea that a simple solution would be to integrate the script (i.e., the "search for active X sessions and run autorandr for each of them using the associated user account" part) into autorandr using a new command line option. It would no longer be necessary to install `pm-suspend` for users that don't use pm-utils then.

**Comment by phillipberndt** [comment]
I have uploaded an attempt to do this in the batch-mode branch.

If started as root, autorandr can now drop privileges to a user's account and run autorandr on his behalf. See lines 811ff. I'd appeciate reviews of that part of the code!

In autorandr, I use a different means for detection of the correct X11 sessions and users. While quite opportunistic (I just iterate over all processes and check the display variable and owner of the process), this might prove to be the reliable variant. @blueyed, you've experienced issues with the 40autorandr script in the past - does the version from the branch work for you?

**Comment by phillipberndt** [comment]
Since there were no further comments, I've pulled these changes to master. Let's see what happens :wink:
