### ISSUE TITLE
Systemd detection broken in xubuntu

### ISSUE THREAD

**Issue by telefax** [phillipberndt/autorandr#48]
I'm setting up autorandr on (X)ubuntu 16.04.

I noticed the proposed fix in systemd detection on arch (https://github.com/phillipberndt/autorandr/issues/38) does not work universally.

On (x)ubuntu 16.04 /proc/1/cmdline outputs **initsplash** which does not exist in /sbin/.
However, **/sbin/init** is linked to **/lib/systemd/systemd**.

This causes the make install command to skip installing the systemd service.

How about checking /proc/1/comm instead (kernel 2.6+...how many use this older kernels?) or using multiple methods?

**/proc/1/comm** Works on RHEL, (X)ubuntu for instance and probably all systemd enabled distributions.

So maybe have something like this in the Makefile:
HAVE_SYSTEMD=(shell grep -q systemd /proc/1/comm && echo "y")

Thanks for an excellent tool btw =)

**Comment by telefax** [comment]
the "40autorandr" file also needs to have "grep -q systemd /proc/1/comm" to make the automagic switching working (Luckily I had **autorandr -c keyboard** shortcut as an escape plan which **always** worked out fine).

As a side note, I had serious problems getting the automagic switching working despite the fix above, there was lots of unexpected behaviour when un/plugging the external monitor. After trying out the retry_branch I can say that it now works as expected! :)

This was on a HP Elitebook 840 G3 using i915 driver.

**Comment by phillipberndt** [comment]
Thanks, that looks reasonable. Fixed.
