### ISSUE TITLE
Support for comments in config files

### ISSUE THREAD

**Issue by blueyed** [phillipberndt/autorandr#50]
It would be nice if comments (lines starting with `#` would be handled in config files (`config` and `setup`)).

**Comment by phillipberndt** [comment]
I guess you'd only have to skip those lines in `from_config_file` and in the list comprehension building `edids` in `load_profiles`, i.e.

    for line in configuration.split("\n"):
        if line:
            line = line.split(None, 1)
            if line[0].startswith("#"):
                continue

and

    edids = dict([ x.strip().split() for x in open(setup_name).readlines() if x.strip() and not x.startswith("#") ])

I don't have the time to test this right now, so please go ahead and file a PR if everything works as  expected!

**Comment by blueyed** [comment]
Thanks!
