### ISSUE TITLE
pm-utils/40autorandr chokes when mutiple sessions exist

### ISSUE THREAD

**Issue by austinglaser** [phillipberndt/autorandr#52]
I've recently installed your version of autorandr, and I was quite excited at the prospect of udev rule integration. So far, however, that hasn't been working.

I've tracked it down to a failure in 40autorandr, in the `find_user` function. In short, the code on lines 19-36 relies on the fact that Active comes before Display in the `loginctl show-session`

On my machine, the output of `loginctl show-session -p Active -p Display 1` (my id is 2) is:

    Display=:0
    Active=no

This is not dependent on the order of the `-p` flags in the above command.

The inner loop therefore gets to the `echo $user` logic before actually parsing the `Active` line. The final effect is that `find_user` reports something like `"sddm myuser"`, an obviously invalid username.

For reference, `systemd --version` reports:

    systemd 229
    +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

I don't think its relevant here, but I've also attached the output of [`xrandr --verbose`](https://github.com/phillipberndt/autorandr/files/443888/xrandr_verbose.txt)

**Comment by blueyed** [comment]
Any idea how I would get the DISPLAY updated with `loginctl` when using `startx`?

`pstree`:

```
  |-login,1202     
  |   `-startx,14973 /usr/bin/startx -- :1 -nolisten tcp
  |       `-xinit,15098 /home/daniel/.xinitrc -- /usr/bin/X :1 -nolisten tcp vt1 -auth /tmp/serverauth.BakPmrragV
  |           |-Xorg,15099 :1 -nolisten tcp vt1 -auth /tmp/serverauth.BakPmrragV
  |           |   |-xf86-video-inte,15102 intel_backlight
  |           |   `-{Xorg},15101
  |           `-session-run-awe,15105 /home/daniel/.dotfiles/usr/bin/session-run-awesome.sh
```

I am `exec`ing it from `~/.profile` (where I have a menu-like selection using `select`).
