### ISSUE TITLE
Autorandr stopped working

### ISSUE THREAD

**Issue by nazar-pc** [phillipberndt/autorandr#63]
I've updated numerous packages on Ubuntu 17.04 today and realized that autorandr doesn't work for me anymore when plugging/unplugging monitor. I've also tried `systemd-change` branch from #62, but it doesn't change anything.

What I'm getting is following:
```
$ env DISPLAY= sudo /usr/bin/autorandr --batch --change --default default                             
Running autorandr as lightdm for display :0
Invalid MIT-MAGIC-COOKIE-1 keyCan't open display :0
Failed to run xrandr (line 430)
```
I'm using Nvidia proprietary driver with nvidia-prime on laptop.

When running `autorandr -c` it works correctly.

Do you have any ideas what might be wrong?

**Comment by phillipberndt** [comment]
Line 801 says

    if uid == 0:

Try replacing it with
    
    if uid < 1000:

Does this change suffice to make it work again?

**Comment by nazar-pc** [comment]
Yes, it does work fine with this change

**Comment by phillipberndt** [comment]
See commit 53d29f9.
