### ISSUE TITLE
/etc/pm/sleep.d/40autorandr fails when run from udev

### ISSUE THREAD

**Issue by forsberg** [phillipberndt/autorandr#68]
When I plug my laptop, running Ubuntu 16.10 and autorandr (from git, installed from debian package version 1.0-16-g855c18b), the screens are not automatically initialized, I have to run autorandr -c manually.

The fault seems to be that /etc/pm/sleep.d/40autorandr tries to write to /var/log/autorandr.log

    Mar  6 07:44:08 besserwisser systemd-udevd[8975]: starting '/etc/pm/sleep.d/40autorandr thaw udev'
    Mar  6 07:44:08 besserwisser systemd-udevd[8974]: '/etc/pm/sleep.d/40autorandr thaw udev'(err) '/etc/pm/sleep.d/40autorandr: 4: /etc/pm/sleep.d/40autorandr: cannot create /var/log/autorandr.log: Read-only file system'
    Mar  6 07:44:08 besserwisser systemd-udevd[8974]: Process '/etc/pm/sleep.d/40autorandr thaw udev' failed with exit code 2.

This is when it's triggered by the udev rule.

I'm confused about what user is actually effective when running that script. Trying to write to /tmp/autorandr.log had the same error. 

Removing the line which tries to log to /var/log/autorandr.log makes everything work, and stdout from autorandr is available in syslog (written there by systemd).

**Comment by phillipberndt** [comment]
Funny indeed - udev runs scripts as root, or should do, at least. I'll be
on vacation throughout March, so I won't be able to provide you with a
patch right away. Removing the line redirecting stdout to the log file
should do the trick, it's not really needed anyway. If you figure out a
good/better solution I'd appreciate a PR!

**Comment by forsberg** [comment]
Very confusing. I added a line which calls 'id', and it indeed reports that it's running as "uid=0(root) gid=0(root) groups=0(root)".

I'll see if I can dig further. But for now, I have it working.
