### ISSUE TITLE
Ask github and @wertarbyte to make this the canonical autorandr repo

### ISSUE THREAD

**Issue by Flowdalic** [phillipberndt/autorandr#79]
Since wertarbyte's autorandr repo is no longer maintained, I suggest to either

- ask @wertarbyte and github to swap the roles of wertarbyte/autorandr and phillipberndt/autorandr, so that the latter becomes the main repo
- just ask github to cut the ties between those two repos

**Comment by phillipberndt** [comment]
I don't think that either is a good idea. Werarbyte wrote the original autorandr, the lineage information "forked from wertarbyte/autorandr" is correct, and the commit history is indeed such that this repo's commits are a superset of his'. Cutting the ties would be a very impolite thing to do if I don't rename the project at the same time, and I don't want to go through that hassle needlessly.

I believe that a better idea would be to place a warning into his repository: "Hey, this is unmaintained. For the time being, please go here: &lt;link>". That's the de facto standard thing to do, see e.g. [pdfpc](https://github.com/pdfpc/pdfpc/), which even does this two levels deep.

I tried to reach out to wertarbyte in https://github.com/wertarbyte/autorandr/issues/36 and https://github.com/wertarbyte/autorandr/pull/33 more than two years ago in this regard. He's obviously no longer interested in maintaining his repo let alone adding a hint about it's state and the existence of this fork. I also filed a feature request with Github for automatically displaying a warning to users visiting a repository which has been inactive for a prolonged period of time but for which active forks exist around the same time, but nothing happened. Apparently, this isn't a pressing issue to them.

Feel free to try to help persuade either party :)
