### ISSUE TITLE
Profile specific scripts should be executed in addition to global ones

### ISSUE THREAD

**Issue by Eisfreak7** [phillipberndt/autorandr#82]
https://github.com/phillipberndt/autorandr/blob/f9800fff9b0dffdf6a42e576c75342054a6d8693/autorandr.py#L789

At least my intuitive understanding would have been, that scripts hin the home directory overwrite scritps in /etc/xdg (as the comment says and is the case), but multiple scripts in the home directory complement each other.

For example I would like to have one global script that notifies my window manager and then one script for each profile that does some profile specific setup (like adjusting the volume).

Also I think there is a documentation issue here: I couldn't find the possibility of per-profile scripts documented anywhere but in the source code.

**Comment by phillipberndt** [comment]
> but multiple scripts in the home directory complement each other

I'm not sure I can follow. Can you give an example?

Or do you mean that you find it unintuitive that e.g. `~/.config/autorandr/postswitch` is only executed if `~/.config/autorandr/<profile>/postswitch` does not exist? If that's the case, note that ``~/.config/autorandr/postswitch.d/some_name` would still be executed even if a profile-specific postswitch handler exists, unless the profile also has a `some_name` script.

**Comment by Eisfreak7** [comment]
Yes, that is exactly what my confusion was about.

Okay that would be a fine workaround then, thanks. I still think executing `<profile>/postswitch` *and* `./postswitch` would be the "better" way to handle this, but that's your call of course.

**Comment by phillipberndt** [comment]
>  I still think executing `<profile>/postswitch` and `./postswitch` would be the "better" way to handle this, but that's your call of course.

In retrospect, I agree. But that's nothing I could change without doing a major version bump.

I'll leave this open as a reminder to improve documentation.

**Comment by Eisfreak7** [comment]
Oh yeah you're right, that would be a breaking change. Thanks for clearing it up and explaining the workaround.

Do you want me to do a PR for the documentation, or do you want to do it yourself?

**Comment by phillipberndt** [comment]
> Do you want me to do a PR for the documentation, or do you want to do it yourself?

If you'd be willing to do that that would be awesome (make sure to add yourself to the contributors list :)) If you're not, that's not a problem at all, I'll come around to improve the documentation myself in a couple of days.

**Comment by Eisfreak7** [comment]
I'll gladly do that, I'm happy if I can help after all the support I received from you :)
