### ISSUE TITLE
Feature Request: Support XRandR 1.3 transformation matrix (e.g. scaling)

### ISSUE THREAD

**Issue by tachylatus** [phillipberndt/autorandr#9]
Case:
* Docked laptop in the middle with a 14 inch 1920x1080 display (eDP1).
* Two 24 inch 1920x1200 monitors on each side (DP1-1 and DP1-2).
* Since the laptop screen is too far away to be readable with the global DPI setting, I use xrandr's "--scale" option to apply a transformation to the output, making the effective resolution smaller than the physical display mode resolution.

Proposal/TODO:
* Change current_cfg_xrandr to parse verbose xrandr query.
* Detect and parse transformation matrix, write "transform none" to config if "filter: " is followed by empty string or "none".
* It should not be necessary to modify load_cfg_xrandr.

Caveats:
* Simple output positioning ("--left-of", "--right-of" etc.) is not handled well in xrandr when transformation is in use. This should not be a problem with autorandr since we use absolute "--pos XxY", but it makes the initial setup harder for the user.

**Comment by phillipberndt** [comment]
I have been using this in the Python version for some time now & it seems to work as expected. So I'll close this. See #12 if you want to implement this for the bash version as well!
