### ISSUE TITLE
Specifying --skip-options via config file

### ISSUE THREAD

**Issue by dondelelcaro** [phillipberndt/autorandr#94]
I'd like to be able to specify `--skip-options gamma` using a config file (`~/.config/autorandr/config`?) or some other mechanism.

[The main reason is because I use redshift, so the gamma changes often, and changing the udev rules to run `autorandr --skip-options gamma --batch` is pretty tedious.]

**Comment by phillipberndt** [comment]
I've implemented this in the `work` branch.

```
$ cat ~/.config/autorandr/settings.ini 
[config]
skip-options=foo,bar
```

Command line values for parameters override the value from the settings file.

**Comment by dondelelcaro** [comment]
Perfect! I'll try to test this shortly

**Comment by dondelelcaro** [comment]
Works perfectly for me with skip-options=gamma. Thanks!

**Comment by phillipberndt** [comment]
Merged.
