### ISSUE TITLE
Cycle/Toggle Profiles

### ISSUE THREAD

**Issue by dramm33** [phillipberndt/autorandr#97]
Is there a way to toggle/cycle between all detected profiles and the default?
I want to bind that to fn + F4.

Currently I have `autorandr --change` binded, but it would be better if I could cycle the profiles.
```
$ autorandr
EASE (detected) (current)
EASE2k (detected)
default2k
TV4k
default4k (current)
```
Also, is it ok to have two `current` profiles?

PS: I could just make a script to get the output of autorandr and change the bind to the next profile, but if there is something already implemented it would make everyones life a whole lot easier.

**Comment by phillipberndt** [comment]
I think that writing a helper script is the easiest solution. Having multiple current profiles is perfectly fine, being current only means that loading this profile wouldn't change anything.

I wouldn't want to add an option to cycle profiles to autorandr, but if you have a suggestion for improvements in the hooks system that would help you achieve your goal then that's something I'll happily accept suggestions/PRs for :)

**Comment by RasmusWL** [comment]
I made a script for this because it is something I do very often. (sometimes I wan't to use the screen on my laptop, but often I don't)

So I would actually support being able to cycle between profiles. But for now, I will try to remember to find the script I'm using when I get home :)

**Comment by dramm33** [comment]
@phillipberndt Thanks for the explanation on the meaning of "current". I will see what I can come up if in the weekend. Is there a place where I can get a list of all the autorandr's variables exposed to the scripts/hooks?

@RasmusWL If you don't mind sharing them, it would be great! That will be really helpful to all who wish do to the same.

**Comment by phillipberndt** [comment]
No, that's only documented inline. The easiest way to get an overview is to grep the output of `set` for AUTORANDR from a hook script.

**Comment by dramm33** [comment]
Worked like charm, thanks!!

**Comment by phillipberndt** [comment]
@RasmusWL thanks a lot! I had completely forgotten about this 🤔

**Comment by C0rn3j** [comment]
@phillipberndt 
>I wouldn't want to add an option to cycle profiles to autorandr

Why would that not be desirable/feasible? 

Personally I want to switch between my monitors, TV and both, and I'd love if autorandr itself had a `--cycle` flag instead of having to rely on a helper script.
