### ISSUE TITLE
Consider using STDOUT instead of STDERR for configuration output of `autorandr`

### ISSUE THREAD

**Issue by dondelelcaro** [phillipberndt/autorandr#98]
One of the users of autorandr in Debian [requested](https://bugs.debian.org/891054) that autorandr use STDOUT instead of STDERR to output its configuration information.

This is totally minor, and I'd be happy to provide a patch and merge request which did this, but I wanted to check first to see if there was a design decision which made STDERR the right output instead of STDOUT.

**Comment by blueyed** [comment]
Makes sense to me.

**Comment by phillipberndt** [comment]
Sorry for the delay, I was on an extended vacation :-) Thanks for this. This came up a couple of times already and I was always quite reluctant about the change as it'd finally break compatibility with the original autorandr. However, now that we have proper version numbers there's nothing speaking against this. (I'll wait with releasing this until I find time to check whether there are some other useful cleanups we could combine with a major version bump though..)
