### ISSUE TITLE
Command line option to output current configuration (and maybe detected outputs?)

### ISSUE THREAD

**Issue by dondelelcaro** [phillipberndt/autorandr#99]
A Debian user [requested](https://bugs.debian.org/891055) that `autorandr` provide a `--print-current` (or some similar option) which output the configuration which was currently used.

Presumably this would be slightly less fragile than parsing the output of `autorandr` itself.

I can make a patch which implements this, but wanted to double check about the option and whether this sounded reasonable.

**Comment by phillipberndt** [comment]
By "configuration which was currently used" you mean the name of the profile(s) that match(es) the current configuration, if any? Sounds reasonable, how about naming it just `--current` (we already have `--config` and `--fingerprint`) and introduce `--detected` while we're at it.

**Comment by dondelelcaro** [comment]
Right, that my understanding too. Those option names sounds perfect to me.

For example, if `autorandr` outputs:

```
workstation (detected) (current)
workstation_video (detected)
television
bigdock
igb_conference_room
undocked
```

`autorandr --current` would output `workstation` and `autorandr --detected` would output:

```
workstation
workstation_video
```

**Comment by phillipberndt** [comment]
Added & in master. I'll try to make a release around Easter.
